Error message for identical variables
jasp-stats/jasp-desktop pull request #3589
Opened 2019-10-11 10:05 UTC by vandenman

Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/290 and adds a unit test for this case.

Error message:

![image](https://user-images.githubusercontent.com/21319932/66643093-58881c80-ec1e-11e9-8336-9353199cdffd.png)

2019-10-16 08:10 UTC, TimKDJ requested changes
Ha, sneaky scatterplot in there as well. It looks very nice!
The legend is a must; the others are comments

2019-10-16 08:10 UTC, TimKDJ commented on JASP-Engine/JASP/R/descriptives.R
> +      "These plots can only be shown for scale variables."
Kinda split on this. On the one hand, it provides useful information to the user. On the other hand, we do not do this anywhere else in JASP. Do you reckon it will be too confusing to show an empty plot until the plot is ready to be computed?

2019-10-16 08:10 UTC, TimKDJ commented on JASP-Engine/JASP/R/descriptives.R
> +      scatterPlot$dependOn(optionContainsValue = list(variables = c(v1, v2)))
I don't think this works right now, but we should definitely make it work...

2019-10-16 08:10 UTC, TimKDJ commented on JASP-Engine/JASP/R/descriptives.R
> +    group <- dataset[, .v(split)]
We should add a legend if there is a split, so it's clear what each color corresponds to

2019-10-16 08:10 UTC, TimKDJ commented on JASP-Engine/JASPgraphs/R/JASPScatterPlot.R
> +  geomSmooth <- if (addSmooth) geom_smooth(formula = y ~ x, method = "loess", se = addSmoothCI) else NULL
You reckon we should add a straight line option, too?

2019-10-16 08:10 UTC, TimKDJ commented on JASP-Engine/JASPgraphs/R/JASPScatterPlot.R
> +  geomSmooth <- if (addSmooth) geom_smooth(formula = y ~ x, method = "loess", se = addSmoothCI) else NULL
I can also totally hear people demanding a different CI level...

2019-10-16 08:14 UTC, vandenman commented
oh oops, the scatterplot was not meant to be in this PR! Until JAGS has been merged, the color scheme can't be adjusted so I wanted to wait with that for a bit. Seem like I accidentally pushed to the wrong branch..

I'll move those changes to a different branch and update the PR accordingly.

2019-10-17 11:18 UTC, TimKDJ commented
Ok.. so that solves it. Let me know when you're finished with edits (and don't forget to remove the print statements)

2019-10-17 12:02 UTC, vandenman commented
@TimKDJ so this PR got waaayyy out of hand...

The things it should do are:

- Check for identical variables in the ANCOVA
- add scatterplots to descriptives
- fix a bug in the plotediting functions and clean up some incorrectly changed files.

Let me know what you think!

2019-10-17 12:59 UTC, TimKDJ commented on JASP-Engine/JASP/R/descriptives.R
> +      JASPgraphs::setGraphOption("palette", options[["colorPalette"]])
This seems kinda error prone. People will forget to do this.
Can't we pass this in as a parameter to graphing functions if we don't want to make persistent changes to JASPgraphs' state?

2019-10-17 13:26 UTC, TimKDJ commented
Ok so like we discussed:

1. remove the html text that tells you why it can't plot for the time being
2. if you add a nominal variable then it errors
```
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.descriptivesPieChart(dataset = dataset.factors, options = options, variable = var)

.descriptivesPieChart_SubFunc(column = column[!is.na(column)], variable = variable, width = options$plotWidth, height = options$plotHeight, title = variable)

JASPgraphs::plotPieChart(tb[, 2], tb[, 1], legendName = variable)

JASPcolors(length(unique(group)))

stop('palette must be character!')
```

2019-10-17 13:26 UTC, TimKDJ commented on JASP-Engine/JASP/R/descriptives.R
> +      JASPgraphs::setGraphOption("palette", options[["colorPalette"]])
And here we can move it to common

2019-10-18 07:10 UTC, TimKDJ approved these changes

2019-10-18 07:10 UTC, merged