Bayesian contingency tables rewrite to jaspResults
jasp-stats/jasp-desktop pull request #3611
Opened 2019-10-21 23:47 UTC by gibbona1

**contingencytablesbayesian.R**
Now uses jaspResults
I've removed the code for the main table and am just calling from `contingencytables.R`

**test-contingencytablesbayesian.R**
Changed the main table unit test to the one in `test-contingencytables.R`

2019-11-05 14:37 UTC, TimKDJ requested changes
Great that you reused a lot of code from the frequentist contingency tables!

A couple of short code comments and I noticed the following while testing:
- [ ] Switching "Row order" from "Ascending" to "Descending" doesn’t change the row order
- [ ] If you add several rows, then the additional contingency tables should be under the existing ones (order should also be deterministic, I think I saw the plots jump around)
- [ ] I don't think the log odds ratio plots needs a legend as it only has one line
- [ ] Setting “Sample” to “hypergeometrics (2x2 only)” and “Alt. Hypothesis” to “Group one < Group two” crashes the analysis: `Error in .contTabBasComputeBF(options, grp.mat[[g]], ready): object 'prop.consistent' not found`
- [ ] If you add only a column variable and tick “Column order” -> “Descending” you get a crash: `Error in rev(lvls, decreasing = TRUE): unused argument (decreasing = TRUE)` (same with row variable and row order)

2019-11-05 14:37 UTC, TimKDJ commented on JASP-Engine/JASP/R/contingencytablesbayesian.R
> +  ready <- length(options$rows > 0) && length(options$columns > 0)
```suggestion
  ready <- length(unlist(options$rows)) > 0 && length(unlist(options$columns)) > 0
```

2019-11-05 14:37 UTC, TimKDJ commented on JASP-Engine/JASP/R/contingencytablesbayesian.R
> +                  "plotPosteriorOddsRatioAdditionalInfo", "priorConcentration")
Shouldn't there be a dependency on the counts and layers?

2019-11-05 14:37 UTC, TimKDJ commented on JASP-Engine/JASP/R/contingencytablesbayesian.R
> +      oddsRatioPlotContainer[[paste0("plots", i, "sub", g)]] <- oddsRatioSubContainer
And shouldn't this then have a dependency on the rows/columns?
Otherwise you don't need the statement at line 168.

Something like
```
$dependOn(optionContainsValue(list(rows=analysis$rows, columns=analysis$columns))
```

2019-11-05 23:30 UTC, gibbona1 commented
> Great that you reused a lot of code from the frequentist contingency tables!
> 
> A couple of short code comments and I noticed the following while testing:
> 
> * [x]  Switching "Row order" from "Ascending" to "Descending" doesn’t change the row order
> * [x]  If you add several rows, then the additional contingency tables should be under the existing ones (order should also be deterministic, I think I saw the plots jump around)
> * [ ]  I don't think the log odds ratio plots needs a legend as it only has one line
> * [x]  Setting “Sample” to “hypergeometrics (2x2 only)” and “Alt. Hypothesis” to “Group one < Group two” crashes the analysis: `Error in .contTabBasComputeBF(options, grp.mat[[g]], ready): object 'prop.consistent' not found`
> * [x]  If you add only a column variable and tick “Column order” -> “Descending” you get a crash: `Error in rev(lvls, decreasing = TRUE): unused argument (decreasing = TRUE)` (same with row variable and row order)

@vandenman does `JASPgraphs::PlotPriorAndPosterior` allow for the legend not to be added?

2019-11-12 09:31 UTC, TimKDJ commented
@vandenman is @gibbona1's request possible?

2019-11-12 10:05 UTC, vandenman commented
Sorry for the late reply. That is possible:
```r
library(JASPgraphs)
# ?PlotPriorAndPosterior # for more info

n <- 100
x <- seq(-3, 3, length.out = n)
dfLines <- data.frame(
  x = x,
  y = c(dnorm(x, 0, 1), dnorm(x, 1, .5)),
  g = rep(c("Prior", "Posterior"), each = n)
)

BF10 <- dnorm(0, 1, .5) / dnorm(0, 0, 1)
p <- PlotPriorAndPosterior(dfLines, BF = BF10, bfType = "BF10")
p$subplots[[3]] <- p$subplots[[3]] + ggplot2::theme(legend.position = "none")
p
```
![image](https://user-images.githubusercontent.com/21319932/68662019-46124300-053c-11ea-9857-1e9df48b301b.png)

2019-11-12 13:54 UTC, gibbona1 commented
Perfect, thanks @vandenman, works great!

2019-11-14 10:06 UTC, TimKDJ commented
> - [ ]  If you add several rows, then the additional contingency tables should be under the existing ones (order should also be deterministic, I think I saw the plots jump around)

This one is not implemented yet; right now you get:
```
[tables first row/column pair]
[plots of all row/column pairs]
[tables second row/column pair]
```
It should be like it was before
```
[tables all row/column pairs]
[plots of all row/column pairs]
```

We should probably make it a little more clear altogether... but let's just return to the old situation for now

2019-11-20 10:51 UTC, TimKDJ commented
>     * [ ]  Setting “Sample” to “hypergeometrics (2x2 only)” and “Alt. Hypothesis” to “Group one < Group two” crashes the analysis: `Error in .contTabBasComputeBF(options, grp.mat[[g]], ready): object 'prop.consistent' not found`

This one still doesn't seem happy:
<img width="1630" alt="Screenshot 2019-11-20 at 11 50 34" src="https://user-images.githubusercontent.com/18737241/69232826-10003f00-0b8c-11ea-8817-25c8ba872db8.png">

2019-12-05 15:03 UTC, TimKDJ commented
I will make the last change

2019-12-05 15:03 UTC, merged