Frequentist (RM) AN(C)OVA rewrites 2
jasp-stats/jasp-desktop pull request #3614
Opened 2019-10-22 09:42 UTC by JohnnyDoorn

Now after a rebase as suggested by Tim

2019-10-22 15:14 UTC, JohnnyDoorn commented
@TimKDJ what went wrong here? I rebased, reinstalled the JASP packages, reran the manageTestPlots and saved the new plots, then added those to this PR... but Travis still says they are different

2019-10-23 15:55 UTC, TimKDJ commented
I'll have a look, can you tell me your versions of:
- jaspResults
- JASPgraphs
- jasptools
- vdiffr
- ggplot2

2019-10-30 12:42 UTC, vandenman requested changes
### ANOVA / ANCOVA
Looks good! Below a small list of things I found. I still need to take a look at the repeated measures and at the code itself though.

Bugs:

- clicking `Vovk-Sellke maximum p-ratio removes the main table
![image](https://user-images.githubusercontent.com/21319932/67858549-bfac3900-fb19-11e9-8814-0133b5ac9b9a.png)

Minor comments:

- I can enter contBinom as covariate.

- the different number of bootstraps looks a bit odd.
![image](https://user-images.githubusercontent.com/21319932/67858743-321d1900-fb1a-11e9-8261-783afce3aa6f.png)

2019-10-30 12:42 UTC, vandenman commented on Resources/ANOVA/qml/AnovaRepeatedMeasures.qml
> +	usesJaspResults: true
```suggestion
```
This is the default, so you can just omit this.

2019-10-30 12:42 UTC, vandenman commented on JASP-Tests/R/tests/figs/deps.txt
> +- vdiffr: 0.3.0
You downgraded `vdiffr`?

2019-10-30 12:42 UTC, vandenman commented on JASP-Tests/R/tests/testthat/test-ancova.R
> +  plot3 <-  results$state$figures[[3]]$obj
these changes are unnecessary?

2019-10-30 12:42 UTC, vandenman commented on JASP-Tests/R/tests/testthat/test-anova.R
> +  results <- jasptools::run("Anova", "test.csv", options, view = FALSE)
```suggestion
  results <- jasptools::run("Anova", "test.csv", options)
```
view argument is redundant (here and in the other calls).

2019-11-13 11:33 UTC, closed without merging