Implement Bain CRAN package and make unit tests
jasp-stats/jasp-desktop pull request #3615
Opened 2019-10-22 10:38 UTC by koenderks

2019-10-29 10:23 UTC, TimKDJ commented
Can you rebase this pr @koenderks? The bain package is added to the framework now

2019-10-29 12:06 UTC, TimKDJ requested changes
Looks good overall, I don't think the suggestions should take very long.

One thing I did notice, but is unrelated to this pr, is that the descriptives is implemented quite inconsistently:

t-tests -> have descriptives table & plot (ci belongs to plot but is also used in table)
anova -> has descriptives table & plot (however ci belongs to table but is also used in plot)
ancova -> only has descriptives plot and no way to set ci

Would be nice to make that consistent

2019-10-29 12:06 UTC, TimKDJ commented on Resources/Help/analyses/BainAncovaBayesian.md
> +2. The levels of the ONE factor are referred to as follows: `factor.levelname`. If, for example, there is a factor age with levels y, m, o. They are reffered to using `agey`, `agem`, and `ageo`, resp
reffered -> referred

2019-10-29 12:06 UTC, TimKDJ commented on Resources/Help/analyses/BainAncovaBayesian.md
> +
This can go I suppose (same for other .md files)

2019-10-29 12:06 UTC, TimKDJ commented on Resources/BAIN/qml/BainAncovaBayesian.qml
> +			text: qsTr("Seed:")
We never put the `:` anywhere, I think it's better to omit

2019-10-29 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/bainancovabayesian.R
> +	eval(parse(text = c1))
Isn't this just (and also for the other similar lines under this and in other files):
```
X[[group]] <- as.factor(X[[group]])
```

If you use `[[` rather than `$` you can use variables as names

2019-10-29 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/bainancovabayesian.R
> +	eval(parse(text = c2))
```
formula <- as.formula(paste(dep, "~", group, "+", cov, "-1"))
lmres <- lm(formula, data = X)
```

Try to avoid eval(parse( when possible

2019-10-29 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/bainttestbayesianonesample.R
> +        plot$setError("Plotting not possible: the results for this variable were not computed.")
This does not have to mean the results were not computed, right?
Shouldn't this pass in the message from the `try-error` object?

2019-10-29 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/bainttestbayesianonesample.R
> +    }
Try to avoid this type of duplication as much as possible. What if you have to add a function parameter to `bain::bain()` in the future? You'd have to add it 5 times, increasing the chance of introducing bugs.

```
    if (type == 1)
      hyp <- paste0("x=", nu)
    else if (type == 2)
      hyp <- paste0("x=", nu, "; x>", nu)
    else if (type == 3)
      hyp <- paste0("x=", nu, "; x<", nu)
    else if (type == 4)
      hyp <- paste0("x>", nu, "; x<", nu)
    else
      hyp <- paste0("x=", nu, "; x>", nu, "; x<", nu)

    result <- bain::bain(tres, hyp)
```

2019-10-29 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/bainttestbayesianonesample.R
> +  return(invisible(result))
There's also some duplication between the `if` statements. I think this would clean it up a little (not tested):

```
.bain_ttest_cran <- function(x, y = NULL, nu = 0, type = 1, paired = FALSE, seed){

  set.seed(seed)
  
  # ONE GROUP
  if (is.null(y) && !paired){
    tres <- bain::t_test(x)  
    lhs <- "x"
    rhs <- nu
  }

  # INDEPENDENT SAMPLES
  if (!is.null(y) && !paired) {
    tres <- bain::t_test(x, y, paired = FALSE, var.equal = FALSE)
    lhs <- "x"
    rhs <- "y"
  }

  # PAIRED SAMPLE
  if (!is.null(y) && paired) {
    tres <- bain::t_test(x, y, paired = TRUE)
    lhs <- "difference"
    rhs <- "0"
  }
  
  if (type == 1)
    hyp <- paste0(lhs, "=", rhs)
  else if (type == 2)
    hyp <- paste0(lhs, "=", rhs, ";", lhs, ">", rhs)
  else if (type == 3)
    hyp <- paste0(lhs, "=", rhs, ";", lhs, "<", rhs)
  else if (type == 4)
    hyp <- paste0(lhs, ">", rhs, ";", lhs, "<", rhs)
  else
    hyp <- paste0(lhs, "=", rhs, ";", lhs, ">", rhs, ";", lhs, "<", rhs)
  
  result <- bain::bain(tres, hyp)

  return(invisible(result))
}
```

2019-10-29 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/bainancovabayesian.R
> +			string <- paste(paste(factor, levels, sep = ""), collapse = " = ")
Shouldn't the collapse still be a `"."`? Because this looks a tad confusing:
<img width="302" alt="Screenshot 2019-10-29 at 12 43 33" src="https://user-images.githubusercontent.com/18737241/67764222-c8353e80-fa49-11e9-8b1c-5017de261f50.png">

2019-10-30 07:09 UTC, koenderks commented on Resources/Help/analyses/BainAncovaBayesian.md
> +2. The levels of the ONE factor are referred to as follows: `factor.levelname`. If, for example, there is a factor age with levels y, m, o. They are reffered to using `agey`, `agem`, and `ageo`, resp
Implemented

2019-10-30 07:09 UTC, koenderks commented on Resources/BAIN/qml/BainAncovaBayesian.qml
> +			text: qsTr("Seed:")
Implemented

2019-10-30 07:10 UTC, koenderks commented on Resources/Help/analyses/BainAncovaBayesian.md
> +
Implemented

2019-10-30 07:10 UTC, koenderks commented on JASP-Engine/JASP/R/bainancovabayesian.R
> +	eval(parse(text = c1))
This function is not from JASP and will be migrated to the bain CRAN package in time

2019-10-30 07:10 UTC, koenderks commented on JASP-Engine/JASP/R/bainttestbayesianonesample.R
> +        plot$setError("Plotting not possible: the results for this variable were not computed.")
Implemented

2019-10-30 07:10 UTC, koenderks commented on JASP-Engine/JASP/R/bainttestbayesianonesample.R
> +    }
This function is not from JASP and will be migrated to the bain CRAN package in time

2019-10-30 07:10 UTC, koenderks commented on JASP-Engine/JASP/R/bainttestbayesianonesample.R
> +  return(invisible(result))
This function is not from JASP and will be migrated to the bain CRAN package in time

2019-10-30 07:11 UTC, koenderks commented on JASP-Engine/JASP/R/bainancovabayesian.R
> +			string <- paste(paste(factor, levels, sep = ""), collapse = " = ")
No, bain actually changed it's hypothesis specification to not include a `.` anymore.

2019-10-30 07:12 UTC, koenderks commented on JASP-Engine/JASP/R/bainancovabayesian.R
> +	eval(parse(text = c2))
This function is not from JASP and will be migrated to the bain CRAN package in time

2019-10-30 08:21 UTC, TimKDJ approved these changes

2019-10-30 08:21 UTC, merged