Rewrite EFA to jaspresults
jasp-stats/jasp-desktop pull request #3616
Opened 2019-10-23 11:30 UTC by vankesteren

Also included several improvements, such as:
- Different factor extraction methods ([#335](https://github.com/jasp-stats/jasp-issues/issues/335), [#89](https://github.com/jasp-stats/jasp-issues/issues/89))
- Kaiser-Meyer-Olkin test and Bartlett's test of sphericity is included as an assumption check ([#79](https://github.com/jasp-stats/jasp-issues/issues/79))

2019-10-31 09:06 UTC, TimKDJ requested changes
So the code looks very clean -- nice!
Two code comments and some issues in a .jasp file:

[problemsInEFA.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/3792948/problemsInEFA.jasp.zip)

2019-10-31 09:06 UTC, TimKDJ commented on JASP-Tests/R/tests/figs/ExploratoryFactorAnalysis/exploratoryfactoranalysis-path-diagram.svg
>  </svg>
This is not right.. where is the reference svg?

2019-10-31 09:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/exploratoryfactoranalysis.R
> +  bartab$addColumnInfo(name = "pval", title = "p-value", type = "number", format = "dp:3;p:.001")
```suggestion
  bartab$addColumnInfo(name = "pval", title = "p", type = "number", format = "dp:3;p:.001")
```
to be in-line with your other table (and most of jasp I think)

2019-11-06 16:33 UTC, vankesteren commented
Alright, fixes done!

2019-11-07 15:06 UTC, TimKDJ commented
Alright look good to me. The only thing is the failing scree plot. I saw you put a skip there for the PCA, so I'm guessing that's also required here.

2019-11-13 08:08 UTC, vankesteren commented
You're right! For the scree plot data is generated. Fixed.

2019-11-13 09:05 UTC, merged