Rewrite linear regression with jaspResults
jasp-stats/jasp-desktop pull request #3620
Opened 2019-10-25 08:32 UTC by TimKDJ

Additionally,

- Made the interface more consistent with logistic regression (renamed and moved "include constant in equation", moved "vovk sellke" and renamed the section "Options" to "Method Specification")
- Changed the forward regression method to start from a null model and then add predictors
- Changed the enter method to name models "H0" and "H1" (like logistic regression) and to always show the intercept model (this was inconsistent previously)
- Changed the numbering of models for stepping procedures (going from 1 to n, rather than sometimes 0 to n or 1 to n)
- Removed pretty much all `try()` statements as they weren't caught anyway :|
- Added more footnotes that state for which table the null model isn't included
- Fixed a bug where the null model is duplicated in backward regression if it contained a nuisance term
- Related to ^ fixed a bug where not all predictors were shown in the Collinearity Diagnostics table
- Fixed a bug where all plots would fail if you added an interaction term -> tick "Partial plots" -> tick other plots

There are 3 `TODO: figure out` statements in the code (just ctrl+f) for scenarios that I was not sure are correctly handled in the old code; it would be great if you could give me input on those @vandenman, @Kucharssim

2019-10-30 11:37 UTC, vandenman commented
I couldn't find any bugs! Looks good to me. Just to reply to the TODOs:

> TODO: figure out what the rule is here, if the same is added and then removed, what should the algorithm do? Stop altogether, or ignore it in the next iteration ignoring in the next iteration seems wrong because you might enter an infinite loop (Add A, Remove A | (Ignore A), Add B, Remove B | (Ignore B), Add A, remove A) stop if the same predictor was added and then removed

I think the algorithm should just stop.

> TODO: figure out if we can show partial plots for non-interaction-term-predictors if any of the other predictors have an interaction term

I have no idea, that's a substantial question.

> TODO: maybe add footnote to casewise diagnostics if there are no cases to show?

Good idea!

> TODO: figure out if this is correct (seems wrong).. the last model fit does not necessarily contain all predictors

Well, you could sort the model by number of predictors so that this assumption always holds. However, the current comment/ code inside that function provides me with too little information to really judge what's going on.

2019-10-30 11:37 UTC, vandenman approved these changes

2019-10-30 12:10 UTC, TimKDJ commented
> Well, you could sort the model by number of predictors so that this assumption always holds. However, the current comment/ code inside that function provides me with too little information to really judge what's going on.

Suppose we use backwards stepping to obtain our models. It starts with all predictors, but as they're all a poor fit, we drop them all, and the final model only contains the intercept. What used to happen is that it still showed "Residuals vs. Covariates" plots for all predictors, but it used the residuals from the intercept only model.

This seems wrong; it should use the residuals from the full model. That's easy enough to fix of course. But I guess my main question is, should it even make these plots, if the model of inference (the final model) does not have any predictors? Because all other plots are specifically related to whatever the "final" model is.

Hope that clarifies it a bit

2019-10-30 15:21 UTC, vandenman commented
That definitely clarifies! In that case, I'd argue that there shouldn't be a plot. It's pretty misleading if only that plot doesn't correspond to the final model.

2019-11-01 11:21 UTC, Kucharssim requested changes
Ok, the code is very good! I found only one issue in the bootstrap, where the confidence interval for the first term gets copied for all terms in the model. Otherwise the analysis seems fine.

![Screen Shot 2019-11-01 at 12 17 48](https://user-images.githubusercontent.com/7093546/68021493-d2ea1080-fca1-11e9-88fd-53e2145419e5.png)

(Also from the User friendliness perspective, maybe it could be worthwhile to have a state for the bootstrap results so that one does not have to resample when enabling/disabling confidence intervals, etc... This is not necessary but would be nice I guess)

2019-11-01 11:33 UTC, Kucharssim commented
> > TODO: figure out if we can show partial plots for non-interaction-term-predictors if any of the other predictors have an interaction term
> 
> I have no idea, that's a substantial question.

Yeah I lean towards not to do it unless we know what are we doing :) Here are some pointers https://stats.stackexchange.com/q/265448. It seems that it is possible but making sure that it is easily interpretable could be tricky.

2019-11-06 13:02 UTC, TimKDJ commented
I fixed the CI of the bootstrap table and added a state to it. Also followed the suggestions you guys gave.

2019-11-06 13:03 UTC, merged