Rewriting Logistic Regression with jaspResults
jasp-stats/jasp-desktop pull request #3621
Opened 2019-10-25 12:26 UTC by gibbona1

**regressionlogistic.R**
Now uses jaspResults
Moved table functions here

**commonglm.R**
Removed old table functions here as they are now in regressionlogistic.R
Some other small changes like line shortening, explicit returns

**test-regressionlogistic.R**
Added error handling unit tests, Confusion Matrix Table and Performance Metrics Table tests, and Removed elements no longer sent to tables (options not ticked in the test) in existing tests.

2019-11-07 14:47 UTC, TimKDJ requested changes
Last one! :)

In addition to my code comments:
- [ ] Without data, tick “Confusion matrix”: Error in terms.formula(formula, data = data): argument is not a valid model**
- [ ] No default empty plots
- [ ] Crash when you specify a dependent variable and tick "Confusion matrix": object ‘jaspResults’ not found**
- [ ] If you untick “Estimates” then you should not see a bootstrap table anymore. How is your qml? I did this for linear regression: https://github.com/jasp-stats/jasp-desktop/blob/eb89aa7dd7a751f654601e62eb090faaab4522cf/Resources/Regression/qml/RegressionLinear.qml#L97 (`bootstrapping` need to be the `id` of the "From" checkbox and you add that line to the "Estimates" checkbox)
- [ ] The confusion matrix needs a dependency on Proportions
- [ ] If you add a term to the null model, then the summary table crashes: attempt to apply non-function**
- [ ] The coefficients table needs a dependency on “Robust standard errors”

** See: [logisticRegressionRewrite.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/3820125/logisticRegressionRewrite.jasp.zip)

2019-11-07 14:47 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +    progress <- .newProgressbar(ticks = ticks, callback = callback, response = TRUE)
We're using a different progressbar in jaspResults.
To use it change the following:
```
ticks    <- options$coeffEstimatesBootstrappingReplicates
progress <- .newProgressbar(ticks = ticks, callback = callback, response = TRUE)
```

which becomes
```
startProgressbar(options$coeffEstimatesBootstrappingReplicates)
```

2019-11-07 14:47 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
And here replace
```
pr <- progress()
response <- .optionsDiffCheckBootstrapLogisticRegression(pr, options)
if(response$status == "changed" || response$status == "aborted")
  stop("Bootstrapping options have changed")
```
with
```
progressbarTick()
```
(so `.optionsDiffCheckBootstrapLogisticRegression()` can also be removed)

2019-11-07 14:47 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
>           identical(attr(bootstrap.summary, "condition")$message, "Bootstrapping options have changed"))
At this point the try error with the message `"Bootstrapping options have changed"` cannot occur anymore, so it can be removed

2019-11-07 14:47 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +    container$dependOn(dependList)
This seems... unnecessary

2019-11-07 14:47 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +      estimatesPlot$dependOn(optionsFromObject = jaspResults[["modelSummary"]],
Nitpick: this is not different between plots, so why not put it on the container instead

2019-11-11 23:24 UTC, gibbona1 commented
> Last one! :)
> 
> In addition to my code comments:
> 
> * [x]  Without data, tick “Confusion matrix”: Error in terms.formula(formula, data = data): argument is not a valid model**
> * [x]  No default empty plots
> * [x]  Crash when you specify a dependent variable and tick "Confusion matrix": object ‘jaspResults’ not found**
> * [x]  If you untick “Estimates” then you should not see a bootstrap table anymore. How is your qml? I did this for linear regression: https://github.com/jasp-stats/jasp-desktop/blob/eb89aa7dd7a751f654601e62eb090faaab4522cf/Resources/Regression/qml/RegressionLinear.qml#L97
>    (`bootstrapping` need to be the `id` of the "From" checkbox and you add that line to the "Estimates" checkbox)
> * [x]  The confusion matrix needs a dependency on Proportions
> * [x]  If you add a term to the null model, then the summary table crashes: attempt to apply non-function**
> * [x]  The coefficients table needs a dependency on “Robust standard errors”
> 
> ** See: [logisticRegressionRewrite.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/3820125/logisticRegressionRewrite.jasp.zip)

2019-11-12 10:42 UTC, TimKDJ approved these changes

2019-11-12 14:12 UTC, TimKDJ commented
Can you rebase? Tests should be working again

2019-11-12 15:13 UTC, merged