Meta analysis rewrite to jaspResults
jasp-stats/jasp-desktop pull request #3623
Opened 2019-10-28 23:26 UTC by gibbona1

**classicalmetaanalysis.R**
Rewrite was fairly extensive, especially since all the plots had to be done in ggplot

**test-classicalmetaanalysis.R**
Will create and test these once my rStudio fixes
Tables will be fine but the plots may be weird

2019-11-04 08:25 UTC, raoelg commented on JASP-Engine/JASP/R/classicalmetaanalysis.R
> -  ### options contains:
Why remove this options description section?

2019-11-04 08:26 UTC, raoelg commented on JASP-Engine/JASP/R/classicalmetaanalysis.R
> +  # Output tables
So everything is now move to side effect functions?

2019-11-04 08:28 UTC, raoelg approved these changes

2019-11-05 09:12 UTC, TimKDJ commented
@vandenman could you take a gander at the ggplot implemetation of the base plots?

2019-11-05 12:53 UTC, vandenman requested changes
Overall I think the code looks fine but there are some bugs (see below). These are probably not all bugs in the current PR, I just stopped after a while. Let me know once they are fixed so I can take another look!


List of bugs:
- [ ] Changing `Method` doesn't update the output. Is it added to the depends?
- [ ] Add two covariates. Under Model Terms, add their interaction. In the table "Coefficients", the last row contains one of the names of the interaction but is empty otherwise.
![image](https://user-images.githubusercontent.com/21319932/68208158-dbf41e00-ffd0-11e9-97b5-d746dcb06335.png)

- [ ] Perhaps the error message of `rma.fit <- tryCatch(...)` should be prefixed with "The metafor package crashed with the following error". Mainly since it's error messages can be a little bit.. odd for people using JASP.
![image](https://user-images.githubusercontent.com/21319932/68208245-11990700-ffd1-11e9-89b0-81f7b0a23da7.png)
![image](https://user-images.githubusercontent.com/21319932/68208411-5e7cdd80-ffd1-11e9-8075-f3acd37a3cbb.png)

- [ ] Funnel plot can crash weirdly:
![image](https://user-images.githubusercontent.com/21319932/68208481-82402380-ffd1-11e9-82b3-6d922390594a.png)

- [ ] Forest plot can crash weirdly:
![image](https://user-images.githubusercontent.com/21319932/68208558-b0bdfe80-ffd1-11e9-945e-4c9e87c2ffae.png)

- [ ] Casewise diagnostics cause missing value error:
![image](https://user-images.githubusercontent.com/21319932/68208668-f67ac700-ffd1-11e9-9014-aaf1457a3b15.png)

- [ ] Diagnostics plot can crash weirdly. Probably related to the forst plot crash since the message is the same.
![image](https://user-images.githubusercontent.com/21319932/68208761-32159100-ffd2-11e9-9d8d-09a8b6c14ad0.png)

- [ ] Covariance matrix bug (perhaps caused by collinear variables):
![image](https://user-images.githubusercontent.com/21319932/68208927-96d0eb80-ffd2-11e9-800b-55e9f022e87c.png)

- [ ] I can toggle `Confidence intervals` but it only does something when `Estimates` is on. Maybe it should be grayed out whenever `Estimates` is unchecked? (I'm aware this behavior was also in the previous release, but I'm not very fond of it).

- [ ] Regression test for funnel plot asymmetry is still base64 encoded:
![image](https://user-images.githubusercontent.com/21319932/68209184-1a8ad800-ffd3-11e9-9996-c76e467cb97f.png)

2019-11-05 12:53 UTC, vandenman commented on Resources/Meta Analysis/qml/ClassicalMetaAnalysis.qml
> +            CheckBox { name: "trimFillPlot";			text: qsTr("Trim-fill analysis")	}
we use tabs in QML and not spaces. See [this link](https://doc.qt.io/qtcreator/creator-indenting-code.html) to change your default settings for Qt creator.

2019-11-05 12:53 UTC, vandenman commented on JASP-Engine/JASP/R/classicalmetaanalysis.R
> +ClassicalMetaAnalysis <- function(jaspResults, dataset = NULL, options, ...) {
Why is the copyright gone?

2019-11-05 12:53 UTC, vandenman commented on JASP-Engine/JASP/R/classicalmetaanalysis.R
> +    #TODO: these need to be polygons/segments as in forest.rma
Is this a leftover TODO or does it still need to be done?

2019-12-11 14:38 UTC, TimKDJ commented
How's this one coming along @gibbona1?

2019-12-11 15:38 UTC, gibbona1 commented
@TimKDJ still having a problem with switching `b64()` and `d64()` to `.v()` and `.unv()`.
Would you be able to have a look? I pushed the latest version

2019-12-12 13:10 UTC, TimKDJ commented
> @TimKDJ still having a problem with switching `b64()` and `d64()` to `.v()` and `.unv()` in
> `.metaAnalysisComputeModel()`.
> Would you be able to have a look? I pushed the latest version

Replace
```
  if (ready) {
    if(length(options$modelTerms) > 0) {
      .vmodelTerms <- NULL
      for (i in seq_along(options$modelTerms)) {
        components   <- options$modelTerms[[i]]$components
        .vmodelTerms <- c(.vmodelTerms, .v(components)) 
        #browser()
        #if (length(components) == 1)
        #  .vmodelTerms <- c(.vmodelTerms, .v(components[[1]]))
        #else {
        #  components.unlisted <- unlist(components)
        #  term.base64         <- paste0(.v(components.unlisted), collapse = ":")
        #  .vmodelTerms        <- c(.vmodelTerms, term.base64)
        #}
      }
      # infer model formula
      #.vmodelTerms <- .v(options$modelTerms)
      .vmodelTerms <- .vmodelTerms[.vmodelTerms != ""]
      #browser()
      formula.rhs <- as.formula(.vmodelTerms)
    } else
      formula.rhs <- NULL
```
with 
```
  if (ready) {
    if (length(options$modelTerms) > 0)
      formula.rhs <- formula(as.modelTerms(.v(options$modelTerms)))
    else
      formula.rhs <- NULL
```

and you should be good to go

2019-12-15 01:15 UTC, gibbona1 commented
> Overall I think the code looks fine but there are some bugs (see below). These are probably not all bugs in the current PR, I just stopped after a while. Let me know once they are fixed so I can take another look!
> 
> List of bugs:
> 
> * [X]  Changing `Method` doesn't update the output. Is it added to the depends?
> * [ ]  Add two covariates. Under Model Terms, add their interaction. In the table "Coefficients", the last row contains one of the names of the interaction but is empty otherwise.
>   ![image](https://user-images.githubusercontent.com/21319932/68208158-dbf41e00-ffd0-11e9-97b5-d746dcb06335.png)
> * [X]  Perhaps the error message of `rma.fit <- tryCatch(...)` should be prefixed with "The metafor package crashed with the following error". Mainly since it's error messages can be a little bit.. odd for people using JASP.
>   ![image](https://user-images.githubusercontent.com/21319932/68208245-11990700-ffd1-11e9-89b0-81f7b0a23da7.png)
>   ![image](https://user-images.githubusercontent.com/21319932/68208411-5e7cdd80-ffd1-11e9-8075-f3acd37a3cbb.png)
> * [X]  Funnel plot can crash weirdly:
>   ![image](https://user-images.githubusercontent.com/21319932/68208481-82402380-ffd1-11e9-82b3-6d922390594a.png)
> * [X]  Forest plot can crash weirdly:
>   ![image](https://user-images.githubusercontent.com/21319932/68208558-b0bdfe80-ffd1-11e9-945e-4c9e87c2ffae.png)
> * [X]  Casewise diagnostics cause missing value error:
>   ![image](https://user-images.githubusercontent.com/21319932/68208668-f67ac700-ffd1-11e9-9014-aaf1457a3b15.png)
> * [X]  Diagnostics plot can crash weirdly. Probably related to the forst plot crash since the message is the same.
>   ![image](https://user-images.githubusercontent.com/21319932/68208761-32159100-ffd2-11e9-9d8d-09a8b6c14ad0.png)
> * [X]  Covariance matrix bug (perhaps caused by collinear variables):
>   ![image](https://user-images.githubusercontent.com/21319932/68208927-96d0eb80-ffd2-11e9-800b-55e9f022e87c.png)
> * [X]  I can toggle `Confidence intervals` but it only does something when `Estimates` is on. Maybe it should be grayed out whenever `Estimates` is unchecked? (I'm aware this behavior was also in the previous release, but I'm not very fond of it).
> * [X]  Regression test for funnel plot asymmetry is still base64 encoded:
>   ![image](https://user-images.githubusercontent.com/21319932/68209184-1a8ad800-ffd3-11e9-9996-c76e467cb97f.png)

2019-12-18 10:03 UTC, TimKDJ commented
> Everything seems to work in R, but I'm getting some `object 'model term' not found` errors when I build JASP and test there (looks like it's from `formula(as.modelTerms(.v(options$modelTerms)))`).

I'm about to make some fixes to the encoding decoding functions which will solve this. However for these fixes to work you must undo your change to classicalmetaanalysis.qml:
```
ModelTermsList { width: parent.width * 5 / 9 }
```
is wrong, there are no null model terms. Replace it with
```
AssignedVariablesList  { name: "modelTerms"; title: qsTr("Model Terms"); listViewType: "Interaction"}
```

2020-01-13 08:40 UTC, TimKDJ commented
@vandenman could you have another look at this?

2020-01-13 10:07 UTC, vandenman requested changes
Overall there were a couple bugs but I think it looks fine and works smoothly.

Bugs:

- [ ] invalid 'times' argument
![image](https://user-images.githubusercontent.com/21319932/72246179-7769c680-35f2-11ea-888f-63e5a8b4f64c.png)

Enter contNormal and contGamma as Effect Size and Effect Size Standard Error. Tick Funnel plot.

- [ ] Diagnostic plots
![image](https://user-images.githubusercontent.com/21319932/72246394-e34c2f00-35f2-11ea-957d-6bec51eb37be.png)

Same variables as above, tick Diagnostic plots under Diagnostics.

- [ ] Changing intercept does not update parameter estimates

![image](https://user-images.githubusercontent.com/21319932/72246729-aa608a00-35f3-11ea-9b17-1090de7ffb44.png)

add contcor1 as covariate, notice that ticking and unticking Include intercept under Model does not change the table of parameter estimates.s

There are some other cosmetic annoyances here and there (e.g., interactions effects are shown with `:` in tables) but I think @TimKDJ and I can sort those out later (we have to do some stuff for the translations anyway).

@gibbona1 can you fix the three bugs listed above?
@TimKDJ after that I think this PR is ready to be merged.

2020-01-21 13:36 UTC, gibbona1 commented
> Bugs:
> 
> * [X]  invalid 'times' argument
> 
> * [X]  Diagnostic plots
> 
> * [X]  Changing intercept does not update parameter estimates

2020-01-22 09:44 UTC, TimKDJ commented
@vandenman: could you check it again?

@gibbona1: you'll need to remake the plots with the latest JASPgraphs versions

2020-01-22 12:16 UTC, gibbona1 commented
> @vandenman: could you check it again?
> 
> @gibbona1: you'll need to remake the plots with the latest JASPgraphs versions

@TimKDJ I have JASPgraphs 0.4.5, jasptools 0.8.5, jaspResults 1.12
Are these all good?

2020-01-22 15:56 UTC, vandenman commented
[metaanalysisBugs.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/4098195/metaanalysisBugs.jasp.zip)

![image](https://user-images.githubusercontent.com/21319932/72909901-0637bb00-3d38-11ea-8893-5b5159c41f6c.png)

Funnel plot and diagnostics plot are still broken?

2020-01-23 11:57 UTC, TimKDJ commented
Yeh the dependencies are correct. I noticed in a [previous PR](https://github.com/jasp-stats/jasp-desktop/pull/3710/files) that some axis stuff needs to be made specific, because otherwise they appear different across platforms, namely:
- set the `limits` argument of the `scale_x_continuous()` and `scale_y_continuous()`
- use `JASPgraphs::getPrettyAxisBreaks()` to get the xbreaks and ybreaks

2020-01-25 19:01 UTC, gibbona1 commented
@vandenman Funnel plot and diagnostics plot seem to work for me
![Screenshot 2020-01-25 18 58 32](https://user-images.githubusercontent.com/33295389/73125977-f670de80-3fa4-11ea-9a53-ee25425a9ba1.png)

2020-01-27 09:07 UTC, vandenman commented
Okay, those plots appear to work, there was a package version issue on my end. At least we'll know that updating the dependencies will crash the module.

2020-01-27 09:07 UTC, vandenman approved these changes

2020-01-28 09:43 UTC, merged