Add Equivalence T-Tests
jasp-stats/jasp-desktop pull request #3803
Opened 2020-01-30 10:42 UTC by boutinb

2020-01-30 15:08 UTC, TimKDJ requested changes
@Jillderon: I know this is Bruno's PR and you can't make changes to it, but I'm still making some code suggestions here. You can change them (if you agree with me that is ;)) in your dynamic module and send the code to Bruno again

I didn't repeat suggestions, but most were relevant for multiple files

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/functionsfromjasp.R
> +#
@boutinb: I'm guessing this entire file should not be included in the JASP R package, as it'll add duplicate functions

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    continue <- int$value < int$abs.error
If `integrate()` returned with an error and `r` is an object of class `try-error`, but the message is not `"maximum number of subdivisions"`, then `int` will be undefined and this will crash hard.

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    bb <- aa
That naming

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    continue <- int$value < int$abs.error
Same same. I guess this function could be merged into the other to reduce duplication?

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    evidenceTxt     = JASPgraphs::parseThis("H[phantom()%in%phantom()]"),
Pretty sure @vandenman deprecated this `phantom()` stuff?

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianindependentsamplesttest.R
> +  if (options$descriptives & is.null(jaspResults[["equivalenceBayesianDescriptivesTable"]]))
You almost always want double logical operators in if statements. This is not a vectorized operation so: `&&`

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianindependentsamplesttest.R
> +.equivalenceBayesianIndTTestComputeResults <- function(jaspResults, dataset, options, ready, errors) {
It doesn't appear that you're ever retrieving this from the state, but instead always recompute.
You need to check if `"stateEquivalenceBayesianIndTTestResults"` already exists in `jaspResults` and if so return that:
```
if (!is.null(jaspResults[["stateEquivalenceBayesianIndTTestResults"]]))
  return(jaspResults[["stateEquivalenceBayesianIndTTestResults"]]$object)
```

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianindependentsamplesttest.R
> +  message <- paste0("I ranges from ", options$lowerbound, " to ", options$upperbound)
`gettextf("I ranges from %1$s to %2$s", options$lowerbound, options$upperbound)`

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianindependentsamplesttest.R
> +                                                    statistic     = "\U003B4 \U02208 I vs. H1",
Did EJ also want it like this? Because it's customary in JASP to only show one BF (e.g., BF10) and then allow the user to select which BF to show with a radiobutton.

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianindependentsamplesttest.R
> +  equivalenceBayesianDescriptivesTable$addColumnInfo(name = "N",          title = gettext("N"),         type = "number")
`type = "integer"`

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +
So at this point it would be good to check if `equivalencePriorPosteriorContainer[[variable]]` exists, because then we don't have to make it again:

```
if (!is.null(equivalencePriorPosteriorContainer[[variable]]))
  next
```

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +  equivalencePriorPosteriorContainer <- createJaspContainer(title = gettext("Equivalence Prior and Posterior"))
You only need to create this if it doesn't exist yet

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    equivalenceTTestPriorPosterior$dependOn(c("priorandposterior", "missingValues", "priorWidth",
All of these dependencies can be placed on the container `equivalencePriorPosteriorContainer` instead (they are not unique to a plot, so can be shared)

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianonesamplettest.R
> +    if (!is.null((results$status))) {
Shouldn't this be `results$status[variable]`?

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianonesamplettest.R
> +      equivalenceBayesianOneTTestTable$addFootnote(message = results$errorFootnotes, rowNames = variable)
And `results$errorFootnotes[variable]`

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianpairedsamplesttest.R
> +  equivalenceBayesianPairedTTestTable$addColumnInfo(name = "separator",   title = " ",                         type = "string")
`type = "separator"` (fixes the misalignment)

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalenceindependentsamplesttest.R
> +    .ttestCheckErrors(dataset, options, "independent")
Don't you want the Bayesian error check function here? Which also checks the number of observations, infinity, etc.

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalenceindependentsamplesttest.R
> +  title <- gettext("90% Credible Interval")
A credible interval in a frequentist analysis -- is that correct? (also isn't 95% more common?)

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalencebayesianindependentsamplesttest.R
> +                                                    statistic     = "\U003B4 \U02208 I vs. H1",
I'm also not sure what `H1` refers to in this context, but that might just be me

2020-01-30 15:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/equivalenceindependentsamplesttest.R
> +      # NOTE: I don't know how to do gettext with paste
[This link might help some](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-translation-rules.md)

2020-01-31 08:31 UTC, vandenman commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    evidenceTxt     = JASPgraphs::parseThis("H[phantom()%in%phantom()]"),
Actually, this is a legit use case of a phantom. If you want to use plotmath to show things like `∈`, then you use `%in%`. However, `%in%` is an operator (like `+`) so it crashes if you don't give it two objects. So you need to do `A%in%B`, except here, we don't really wanna show `A` nor `B`. So the "solution" is to have an empty phantom, one that doesn't do any spacing, be an element of an empty phantom (yay R!).

2020-01-31 08:33 UTC, TimKDJ commented on JASP-Engine/JASP/R/commonequivalencefunctions.R
> +    evidenceTxt     = JASPgraphs::parseThis("H[phantom()%in%phantom()]"),
Fair enough!

2020-02-07 14:07 UTC, boutinb commented
@TimKDJ I have added the last changes from Jill. Do you prefer to check them now, or first to merge the PR?

2020-02-07 14:09 UTC, TimKDJ commented on JASP-Engine/JASP/R/functionsfromjasp.R
> +# Copyright (C) 2013-2018 University of Amsterdam
You added this one again @boutinb

2020-02-07 14:18 UTC, boutinb commented on JASP-Engine/JASP/R/functionsfromjasp.R
> +# Copyright (C) 2013-2018 University of Amsterdam
I have just removed it.

2020-02-07 14:23 UTC, TimKDJ commented
Give me a few minutes to test if they all work and if so we can merge and perform further testing in the nightly

2020-02-07 15:21 UTC, merged