Missing Data Library items in the Dutch version
jasp-stats/jasp-desktop pull request #3857
Opened 2020-02-12 13:31 UTC by FransMeerhoff

- Switching to the Dutch Data Library some items in the Bain samples are missing.
see https://github.com/jasp-stats/jasp-test-release/issues/508

2020-02-13 11:59 UTC, koenderks requested changes

2020-02-13 11:59 UTC, koenderks commented on Resources/Data Sets/index_nl.json
> +          "path": "sinoForest.jasp",
Het voorbeeldbestand in JASP

2020-02-13 11:59 UTC, koenderks commented on Resources/Data Sets/index_nl.json
> +        "description": "Dit JASP-bestand toont een Bain-regressie met behulp van de Sesamstraat gegevens. <br> <br> <i> Gegevensset opgenomen in het bain R-pakket. <\ / I>",
Bain regressie

2020-02-18 10:07 UTC, FransMeerhoff commented on Resources/Data Sets/index_nl.json
> +          "path": "sinoForest.jasp",
OK

2020-02-18 10:07 UTC, FransMeerhoff commented on Resources/Data Sets/index_nl.json
> +        "description": "Dit JASP-bestand toont een Bain-regressie met behulp van de Sesamstraat gegevens. <br> <br> <i> Gegevensset opgenomen in het bain R-pakket. <\ / I>",
OK

2020-02-18 14:06 UTC, TimKDJ commented
All good @koenderks?

2020-02-19 09:57 UTC, koenderks approved these changes
Looks good to me

2020-02-19 09:57 UTC, merged