Fix bugs in logistic regression
jasp-stats/jasp-desktop pull request #3875
Opened 2020-02-19 10:07 UTC by vandenman

Fixes:

https://github.com/jasp-stats/jasp-test-release/issues/556
https://github.com/jasp-stats/jasp-test-release/issues/557
https://github.com/jasp-stats/jasp-test-release/issues/560

The changes are a bit more drastic than I wanted to, but that's what happens I guess. In the unit tests, the columns of one table got reordered (don't ask me why). The other unit test got smaller since the CI is no longer shown by default.

@FBartos can you verify that the issues are fixed?
@TimKDJ can you take a general look at the code to see if I did anything stupid?

2020-02-19 11:54 UTC, TimKDJ reviewed
Some minor suggestions, looks good in general. I couldn't really judge the additional statistics for the bootstrapping though

2020-02-19 11:54 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +  estimatesTableBootstrap$addFootnote(ngettext(1 * options$robustSEOpt,
I'm not sure `ngettext()` is the best solution for this. I think this creates a special "plural" entry type in the .po file, which would not be appropriate here. Can you verify this @FransMeerhoff?

2020-02-19 11:54 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +          else if(identical(attr(result.bootstrap.ci, "condition")$message, "estimated adjustment 'a' is NA")){ #Does this still work if we turn on translations? I'm gonna guess not...
It'll only stop working if the package uses `gettext()` and includes a .po file for the language.. I suppose we made error message checking even more fragile ;)

2020-02-19 11:54 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +    estimatesTableBootstrap$addColumnInfo(name = "std",   title = gettextf("Standardized%s", "\u207A"), type = "number", format="dp:3")
Good to add the footnote too, if you add the symbol for the footnote (not sure if people would look at different tables for the symbol)

2020-02-19 16:59 UTC, FBartos approved these changes

2020-02-20 10:15 UTC, TimKDJ requested changes

2020-02-20 10:15 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +    estimatesTableBootstrap$addFootnote("Coefficient estimate is based on the median of the bootstrap distribution.")
2x `gettext()`

2020-02-20 10:15 UTC, TimKDJ commented on JASP-Engine/JASP/R/regressionlogistic.R
> +  ciTitle <- sprintf(ngettext(1*addBCA,
I'd un-`ngettext()` this one too

2020-02-20 11:20 UTC, TimKDJ approved these changes

2020-02-20 11:20 UTC, TimKDJ commented
Thanks for taking care of the logistic regression issues!

2020-02-20 11:21 UTC, merged