Updates to network analysis
jasp-stats/jasp-desktop pull request #4077
Opened 2020-05-12 11:36 UTC by vandenman

Fixes https://github.com/jasp-stats/jasp-issues/issues/702
Analog of https://github.com/jasp-stats/Network/pull/1

2020-05-12 12:10 UTC, vandenman commented
The first commit failed on Travis because the tests for the centrality table had an extra column.

2020-05-14 10:19 UTC, TimKDJ commented
Can you rebase?

2020-05-14 11:35 UTC, vandenman commented
@TimKDJ I think I rebased the correct commits away..

2020-06-02 09:08 UTC, TimKDJ requested changes
There were a few problems I found with these changes:
- [x] The `Expected influence` column is empty, instead it shows a column titled `NA` next to it
- [x] I get the error `invalid 'width' argument` in the centrality plot

[bugs_network_pr.zip](https://github.com/jasp-stats/jasp-desktop/files/4716051/bugs_network_pr.zip) (rename)

2020-06-02 09:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/networkanalysis.R
> +
It's one thing to remove unnecessary spacing, but to add it? ;)

2020-06-02 09:08 UTC, TimKDJ commented on JASP-Engine/JASP/R/networkanalysis.R
> +      groups <- groups[nonEmpty]
I'm not sure where this orginates exactly, but to be sure: we're certain `groups` will always have at least one non empty entry?

2020-06-02 09:45 UTC, vandenman commented on JASP-Engine/JASP/R/networkanalysis.R
> +
hahaha I'm not sure how that happened but I'll get rid of it :p

2020-06-02 18:04 UTC, vandenman commented on JASP-Engine/JASP/R/networkanalysis.R
> +      groups <- groups[nonEmpty]
`groups` is based on a QML element that cannot be empty.

2020-06-03 06:47 UTC, vandenman commented
@TimKDJ refreshing the jasp file should fix all the errors. In addition, I made a mistake while rebasing and accidentally removed changes to the QML file (which caused the width error).

2020-06-05 12:37 UTC, TimKDJ approved these changes

2020-06-05 12:41 UTC, merged