Gettextf fixes and prepare .po files for translators
jasp-stats/jasp-desktop pull request #4105
Opened 2020-05-29 12:23 UTC by FransMeerhoff

- gettextf fixes
- updating .po files
- remove html unicode #4104 
-remove unicod from parameter list

2020-06-04 09:59 UTC, boutinb requested changes
I wonder why the unicode characters cannot be directly set with their real character: e.g  \u03B8 as θ

2020-06-04 09:59 UTC, boutinb commented on JASP-Desktop/JASP-Desktop.pro
Should be generate always the language files?

2020-06-04 09:59 UTC, boutinb commented on JASP-Desktop/widgets/listmodelcustomcontrasts.cpp
Change it to Log::log()

2020-06-05 15:01 UTC, TimKDJ commented
Are all 700 `gettextf()`'s checked now?

2020-06-11 12:44 UTC, merged