Reliability module
jasp-stats/jasp-desktop pull request #4155
Opened 2020-06-23 07:07 UTC by juliuspf

fixes https://github.com/jasp-stats/jasp-test-release/issues/847
fixes https://github.com/jasp-stats/jasp-test-release/issues/848
fixes https://github.com/jasp-stats/jasp-test-release/issues/846

2020-06-24 14:44 UTC, juliuspf commented
In addition, the PR fixes issues with
i) the footnotes when Bayesian - missings - listwise deletion- footnotes
ii) the footnote when variables are deleted from the window, and the footnote would be empty, which crashed then
iii) being able to select no reliability coefficient, but item statistics such as item-rest correlation

2020-06-25 14:38 UTC, TimKDJ commented on JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R
> +  on.exit(sink(NULL))
Remove this please

2020-06-26 07:45 UTC, vandenman requested changes
Code looks ok, I'll take a look at the behavior in JASP now.

2020-06-26 07:45 UTC, vandenman commented on JASP-Engine/JASP/R/reliabilityAnalysisBayesian.R
> +		}
Please don't mix tabs and spaces and use 2 spaces for indents in R code.

2020-06-26 07:45 UTC, vandenman commented on JASP-Engine/JASP/R/reliabilityAnalysisBayesian.R
> +	                                       limits = c(range(xBreaks)))
```suggestion
	                                       limits = range(xBreaks))
```
`c()` doesn't do anything right?

2020-06-26 08:44 UTC, vandenman commented
- [x] fixes jasp-stats/jasp-test-release#887
- [x] fixes jasp-stats/jasp-test-release/issues/889 
- [x] fixes jasp-stats/jasp-test-release/issues/891
- [x] fixes jasp-stats/jasp-test-release#848

- [ ] I couldn't test jasp-stats/jasp-test-release#847
![image](https://user-images.githubusercontent.com/21319932/85837227-1268ee00-b798-11ea-8f28-b204a225b0c1.png)

- [ ] Doesn't fix jasp-stats/jasp-test-release/issues/846

![image](https://user-images.githubusercontent.com/21319932/85837687-a5098d00-b798-11ea-8511-d6ed27c90a69.png)

open the jasp file in the issue, click refresh all and the issue persists.

2020-06-26 08:56 UTC, juliuspf commented
> * [ ]  I couldn't test [jasp-stats/jasp-test-release#847](https://github.com/jasp-stats/jasp-test-release/issues/847)

Well, that is probably because the R-package has not been updated.

2020-06-26 11:06 UTC, closed without merging