Updates - Distributions module
jasp-stats/jasp-desktop pull request #4216
Opened 2020-08-05 14:03 UTC by Kucharssim

Details here https://github.com/jasp-stats/DiscoverDistributions/pull/1 + new unit tests

2020-08-05 15:46 UTC, Kucharssim commented
Travis failed to build...

2020-08-06 12:59 UTC, Kucharssim commented
@AlexanderLyNL would you be able to check it out? If not let's ask someone else...

2020-08-06 14:14 UTC, AlexanderLyNL commented
Perhaps Don or Johnny can have a look at this.

2020-08-28 07:16 UTC, boutinb commented
@JohnnyDoorn If you can't review it, maybe ask @vandenman too do it.

2020-08-28 09:08 UTC, vandenman requested changes
I haven't tested it in JASP yet, but most of the code looks ok to me.

I've probably said this before but there is quite some code duplication. It might be worthwhile to think of some ways to minimize that. For example, the bodies of `LDlogistic` and `LDlognormal` look nearly identical to me. There are plenty of ways to circumvent duplicating the code like this (e.g., using a function, using S3 classes, or using R6 classes).

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLogistic.R
> +  options[['rFun']]   <- rlogis
```suggestion
  options[['pdfFun']] <- stats::dlogis
  options[['cdfFun']] <- stats::plogis
  options[['qFun']]   <- stats::qlogis
  options[['rFun']]   <- stats::rlogis
```
a little bit pedantic, but when we switch to modules we'll either need to prepend all of these with `stats::` or otherwise we need to import in the namespace (using roxygen2, ideally). Doing it now already might alleviate that step. If you prefer doing this with roxygen2 you can ignore this comment :)

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLogistic.R
> +  }
is this else intentionally empty?

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLogistic.R
> +  }
also intentionally empty?

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLognormal.R
> +  options[['rFun']]   <- rlnorm
`stats::` or ignore if you want to use roxygen2

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLognormal.R
> +  }
shouldn't this be a function? I'm sure it works fine but there is some code duplication going on.

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLognormal.R
> +  }
empty else

2020-08-28 09:08 UTC, vandenman commented on JASP-Engine/JASP/R/ldLognormal.R
> +  }
empty else

2020-08-28 09:08 UTC, JohnnyDoorn commented
I will test later today, or else tomorrow!

On Fri, Aug 28, 2020, 09:16 bruno boutin <notifications@github.com> wrote:

> @JohnnyDoorn <https://github.com/JohnnyDoorn> If you can't review it,
> maybe ask @vandenman <https://github.com/vandenman> too do it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/pull/4216#issuecomment-682369578>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADX2BC3GYITBQUPKTWNAFCTSC5KUDANCNFSM4PVQPWCQ>
> .
>

2020-09-02 15:27 UTC, Kucharssim commented
Thanks @vandenman for the feedback! I reduced some code duplication and added `stats::` wherever needed. There is still some code duplication left, but the most obvious sources are reduced, I think. I will need to think about the leftovers next time.

2020-09-03 07:35 UTC, vandenman requested changes
So I'm not sure if this is intended:

![image](https://user-images.githubusercontent.com/21319932/92084882-4f6ce480-edc8-11ea-807b-8fdc007fcfac.png)

Open the Chi-square distribution, sample 100 new observations to a new variable with k = 5 and lambda = 0. Then try to estimate the parameters of this distribution. The result is an error. It could be that lambda = 0 is a corner case as other values do work (e.g., lambda = 2). If so, then should we maybe change the default value for lambda to something else?

The rest of the changes look good to me!

2020-09-03 10:39 UTC, Kucharssim commented
> So I'm not sure if this is intended:

Yeah, this is annoying. You are correct that lambda = 0 is a boundary value and this causes problems when fitting. One problem was that I set the bounds of lambda incorrectly, and that is fixed now. It does not really fix the issue, though.

> then should we maybe change the default value for lambda

The problem is that lambda is the noncentrality parameter, and so defaulting it to 0 makes sense, as that leads to the standard chi-squared distribution. I am more inclined to rather include an option where you can specify which parameters to estimate and which parameters to keep fixed at their specified values. In case of chi-squared, we could have default lambda = 0 and fixed (but possibility to let it free). I am currently writing this feature in a different branch, but it's not ready yet.

2020-09-03 12:12 UTC, vandenman commented
> Also, I need to improve the robustness of MLE in general. I thought using the specialised fitdistplus package would be fine as it usually works well, but in reality it just makes the implementation in JASP more awkward and harder to debug than just to call optim() - in hindsight, I would do it differently. But I will need to do it later.

Yeah a package like fitdistrplus is nice when first writing it up but it may turn out to be not flexible enough later. Either way, the code looks fine to me, if Travis is happy then I'm happy.

2020-09-03 12:31 UTC, EJWagenmakers commented
"Optim" is very buggy though -- it sometimes forgets previous better solutions and reports an inferior one
E.J.

2020-09-03 12:47 UTC, vandenman approved these changes

2020-09-10 10:44 UTC, AlexanderLyNL commented
@Kucharssim Could you please make a corresponding PR to the module?

2020-09-10 10:44 UTC, merged

2020-09-10 10:56 UTC, Kucharssim commented
> @Kucharssim Could you please make a corresponding PR to the module?

Ah yeah, it's here https://github.com/jasp-stats/jaspDistributions/pull/1, but I need to add the changes based on Don's feedback. I forgot about it - i'll do it asap.