Tweaks Wilcoxon tests (freq/Bayes)
jasp-stats/jasp-desktop pull request #4228
Opened 2020-08-10 15:31 UTC by JohnnyDoorn

- Adjust the helpfiles to clarify how we obtain Wilcoxon test statistic
- Remove decorrelation steps Wilcoxon (@vandenman was right in the end!)

2020-08-11 07:53 UTC, vandenman requested changes
Looks fine to me but Travis complains about:
```r
test-ttestbayesianindependentsamples.R:36: failure: Main table results match for Wilcoxon test
New table is not equal to old table:
New table value `0.277730185316156` (col `BF`, row 1) does not exist in old table
New table value `1.00447417926979` (col `rHat`, row 1) does not exist in old table
Old table values `0.395004853845122`, `0.999374433542238` do not exist in new table
```
Furthermore, I guess we remove the decorrelation step in response to an issue? can you link the issue in your PR?

2020-08-11 09:21 UTC, JohnnyDoorn commented
Yes, nice that the unit test are working again! updated the code, and linked the issues in my OP

2020-08-11 11:35 UTC, vandenman approved these changes

2020-08-11 13:18 UTC, merged

2020-08-13 09:42 UTC, AlexanderLyNL commented
@JohnnyDoorn can make the same PR to master please?