Add performance plots for logistic regression
jasp-stats/jasp-desktop pull request #4234
Opened 2020-08-12 09:12 UTC by maltelueken

Fixes jasp-stats/jasp-issues#277, fixes jasp-stats/jasp-issues#890

I added options for ROC and PR plots to the logistic regression function. The cutoffs steps can be specified manually and cutoff labels can be added if necessessary.
![image](https://user-images.githubusercontent.com/63114869/89997504-813cd080-dc8c-11ea-854c-147b43c01091.png)

2020-08-12 16:03 UTC, Kucharssim commented
The new unit tests fail. Did you run `manageTestPlots()`, @maltelueken?

2020-08-12 16:26 UTC, maltelueken commented
Yeah I did (that's why I made the last commit with the updated test plots). I also ran testAnalysis() and it worked fine on my computer. My git repository is also up to date with this branch.

2020-08-12 17:02 UTC, Kucharssim requested changes
Ok, the unit tests failed on my computer, so here is the code suggestion on how to fix the unit tests. After fixing the code, be sure to run the `manageTestPlots()` and validate the new plots. This should do it!

2020-08-12 17:02 UTC, Kucharssim commented on JASP-Tests/R/tests/testthat/test-regressionlogistic.R
> +  expect_equal_plots(testPlot, "prPlot", dir="RegressionLogistic")
```suggestion
  options$rocPlotOpt <- TRUE
  options$prPlotOpt  <- TRUE

  results <- jasptools::run("regressionlogistic", "lowbwt.csv", options, makeTests = TRUE)
  
  plotName <- results[["results"]][["performancePlots"]][["collection"]][["performancePlots_rocPlot"]][["data"]]
  testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
  expect_equal_plots(testPlot, "rocPlot", dir="RegressionLogistic")
  
  plotName <- results[["results"]][["performancePlots"]][["collection"]][["performancePlots_prPlot"]][["data"]]
  testPlot <- results[["state"]][["figures"]][[plotName]][["obj"]]
  expect_equal_plots(testPlot, "prPlot", dir="RegressionLogistic")
```

You don't need to run the tests twice, once is enough. In the suggestion, I added the `plotName` statements so that you do not rely on the numeric indexing. Also, you need to subset the object from the results (therefore the added `[["obj"]]`

2020-08-12 18:43 UTC, maltelueken commented
Somehow it throws an error for the commit with the validated plots (but it worked before, for some reason). Could we just remove the last commit then?

2020-08-12 18:57 UTC, Kucharssim requested changes
Well, interesting that it worked even before updating the plots... Travis now failed not because of the tests, but because the build failed. I now see that I made an error in the suggestions as well, you can just commit the suggestion below and Travis will rebuild. The tests currently pass on my computer, it should go well this time.

2020-08-12 18:57 UTC, Kucharssim commented on JASP-Tests/R/tests/testthat/test-regressionlogistic.R
> +  results <- jasptools::run("regressionlogistic", "lowbwt.csv", options, makeTests = TRUE)
```suggestion
  results <- jasptools::run("regressionlogistic", "lowbwt.csv", options)
```

This printed out a lot of garbage...

2020-08-12 19:45 UTC, maltelueken commented
Alright, let's hope the best!

2020-08-12 20:47 UTC, Kucharssim approved these changes
Alright, the code is very nice, plots as well! Can be merged now.

2020-08-12 21:09 UTC, merged

2020-08-13 07:45 UTC, TimKDJ commented
@AlexanderLyNL can you make sure that everything you merge also ends up in the modules?

2020-08-13 08:25 UTC, AlexanderLyNL commented
How?

2020-08-13 08:27 UTC, Kucharssim commented
The PR is ready here: https://github.com/jasp-stats/jaspRegression/pull/4

2020-08-13 08:28 UTC, TimKDJ commented
> How?

Just by reminding people :)

2020-08-13 08:29 UTC, Kucharssim commented
> Just by reminding people :)

This was my bad, not Alexander's, sorry about that! It's fixed now

2020-08-13 08:41 UTC, AlexanderLyNL commented
Everybody's doing such a great job with this, that I didn't even noticed it. I'll remind people about it next time!

2020-08-13 09:15 UTC, TimKDJ commented
If you could have a look at the previous ones you've merged that'd be pretty awesome (e.g., https://github.com/jasp-stats/jasp-desktop/pull/4228). This situation is not very nice, but fortunately it's only for one release

2020-08-13 09:18 UTC, AlexanderLyNL commented
PR to master?

2020-08-13 09:22 UTC, TimKDJ commented
Yep