Speed up An(c)ova and .v
jasp-stats/jasp-desktop pull request #4244
Opened 2020-08-18 12:46 UTC by vandenman

Should fix https://github.com/jasp-stats/jasp-issues/issues/918 (but let's not close that issue when merging this, let's wait with that until the contributors in that thread can verify the timings).

Here a zip file with the profiling of this PR vs Stable.

[profileAnova.zip](https://github.com/jasp-stats/jasp-desktop/files/5090352/profileAnova.zip)

The slowdown/ speedup in a nutshell:

Take the flame graph for stable:

![image](https://user-images.githubusercontent.com/21319932/90512920-2ceb9200-e15f-11ea-9fd4-b21d5113e583.png)

The total time is 20930 ms of which 15340 ms are spend inside `.anovaCheckErrors`. If we zoom in on all the tiny bars we see:

![image](https://user-images.githubusercontent.com/21319932/90513211-8bb10b80-e15f-11ea-9cb4-aeb998747a46.png)

For some reason, `.v` is executed a million times (or more) and it's rather slow. The culprit here seems `.findFun` / `getAnywhere`. I've changed that into:

```r
if (jaspResultsCalledFromJasp())
  return(get(name, .GlobalEnv))
else
  return(getFromNamespace(name, asNamespace("jasptools")))
```

Furthermore, `.v` is called so often because `.applyOnGroups` calls it inside its lambda. I've now ensured that it's only called once outside of the lambda.

A final optimization I did was inside `.anovaCheckErrors`. The key there is that multiple calls to `.hasErrors` could be combined to one and that we don't need to loop over all model terms, but instead over the model terms with highest interactions. For example, if the variance is nonzero after grouping on A & B & C, it's certain that the variance is also nonzero when grouping on A, B, C, A & B, A & C, and B & C (which is what the old code did twice).

Here's the flame graph for this PR:

![image](https://user-images.githubusercontent.com/21319932/90513781-7688ac80-e160-11ea-8284-0b9538fc54cb.png)

The total run time is now 5390 ms of which 360 ms are spend inside `.anovaCheckErrors`.

2020-08-18 12:53 UTC, EJWagenmakers commented
nice!

2020-08-18 20:42 UTC, AlexanderLyNL reviewed
It looks fine to me, but I'm not sure if I'm the best person to look into this.

2020-08-18 20:42 UTC, AlexanderLyNL commented on JASP-Engine/JASP/R/commonerrorcheck.R
> +
Not really a part of this PR, but can we use the same structure using plyr in the above clause.

2020-08-27 15:53 UTC, AlexanderLyNL commented
@TimKDJ Could you please have a look this one as well? Then if it's good we can merge it.

2020-08-28 12:06 UTC, TimKDJ requested changes
Good job on the investigative work.
Theoretically it sounds ok, but I could not verify that this solves the linked issue.
I tried the dataset linked [here](https://github.com/jasp-stats/jasp-issues/issues/918#issuecomment-667514078), but this already runs in about 2 seconds for me in the latest nightly.

2020-08-28 12:06 UTC, TimKDJ commented on JASP-R-Interface/jaspResults/DESCRIPTION
> +Version: 1.15
Can you also adjust the `JASP_R_INTERFACE_MINOR_VERSION` in JASP.pri?

2020-08-28 12:06 UTC, TimKDJ commented on JASP-R-Interface/jaspResults/R/writeImage.R
> +      return(getFromNamespace(name, asNamespace("jasptools")))
This work for `jasptools`, but it will break `jaspTools` ([I dump this stuff into the globalEnv now](https://github.com/jasp-stats/jaspTools/blob/f2f3d1bd7a4cc1577748e35868860837cf36aca2/R/rbridge.R#L4-L16)) . To make sure everything keeps on working, maybe you could edit `jasptools` to put [the stuff](https://github.com/jasp-stats/jasp-desktop/blob/bf833e55c58f8e186dd2760ffeb46fb8f456f2e8/Tools/jasptools/R/rbridge.R#L3-L11) in globalEnv too?
Then this `.findFun` function can actually just go altogether.

2020-08-28 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/ancova.R
> +      dataset              = dataset,
Do we also require this `.hasErrors()` to be inside the loop?
Aren't we just checking to see if all factors have enough factor levels?

2020-08-28 12:06 UTC, TimKDJ commented on JASP-Engine/JASP/R/ancova.R
> +    # then all the two-way interactions composed of variables from the three-way interaction will pass.
Nice :)

2020-08-28 12:22 UTC, vandenman commented on JASP-R-Interface/jaspResults/R/writeImage.R
> +      return(getFromNamespace(name, asNamespace("jasptools")))
we could do that, or something like:
```r
    if ("jasptools" %in% loadedNamespaces())
      return(getFromNamespace(name, asNamespace("jasptools")))
    return(get(name, .GlobalEnv))
```
I'd rather not adjust jasptools :)

2020-08-28 12:24 UTC, TimKDJ commented on JASP-R-Interface/jaspResults/R/writeImage.R
> +      return(getFromNamespace(name, asNamespace("jasptools")))
Fine by me too. We'll just remove the line once `jasptools` is put to rest

2020-08-28 12:53 UTC, vandenman commented on JASP-Engine/JASP/R/ancova.R
> +      dataset              = dataset,
I think you're absolutely right, I'll add this to the first call to `.hasErrors` that also checks for infinity. Furthermore, the check `factorLevels` seems to check the number of unique observations when you pass continuous variables as the target. But we're already checking the number of observations and the variance so we never needed to do that... I'll also change that.

2020-09-01 08:11 UTC, TimKDJ approved these changes

2020-09-01 08:12 UTC, merged