Fix for the prior posterior plot incorrectly switching the bf10 and bf01 label
jasp-stats/jasp-desktop pull request #4254
Opened 2020-08-24 14:53 UTC by JTPetter

Fixes jasp-stats/jasp-issues#796

https://github.com/jasp-stats/jaspSummaryStatistics/pull/3

2020-08-28 09:41 UTC, akashrajkn requested changes

2020-08-28 09:41 UTC, akashrajkn commented on JASP-Engine/JASP/R/commonsummarystatsttestbayesian.R
> +    yAxisLegendRobustnessPlot = bfPlotsH1H0,
This causes the unit tests to fail. (The robustness plot expects a string. Can you make the necessary change?)

2020-09-04 11:43 UTC, akashrajkn approved these changes

2020-09-04 11:45 UTC, AlexanderLyNL commented
@JTPetter could you please also make this PR to the module?

2020-09-04 11:47 UTC, merged