Make the interface to choose the fonts a bit simpler.
jasp-stats/jasp-desktop pull request #4262
Opened 2020-08-31 10:12 UTC by boutinb

Remove the checkbox to set the default font, and add it as default in the DropDown.
Remove warning due to form not being defined when GridLayout is used outside of an analysis form.

2020-08-31 12:02 UTC, JorisGoosen commented on JASP-Desktop/gui/preferencesmodel.cpp
> +	{
Why all these extra braces man... Waste of space

2020-08-31 12:12 UTC, JorisGoosen requested changes
Why did you simplify it anyway?

For me it is now **very hard** to get back to the "default" font:
![Screenshot_2020-08-31_141014](https://user-images.githubusercontent.com/29062713/91718509-ca00ee80-eb93-11ea-8943-17ec2b3d6795.png)

I can also not type in the box, there is no scrollbar so I can only scroll with the mouse but that goes very slow...
I have a lot of fonts on my system apparently...

For me the "default" button was good, at least you can go back to default easily.

2020-08-31 12:12 UTC, JorisGoosen commented on Resources/Help/preferences/prefsui_nl.md
> +Hier kun je aangeven welke lettertype wordt gebruikt door de interface (file menu, ribbon bar en analysisopties paneel), de R, Lavaan of JAGS code, of de analyseresultaat paneel. Als je geen keuze ma
Dit is geen correct nederlands...

"Hier kun je aangeven welk lettertype gebruikt wordt door de interface (bestandsmenu, ribbon balk en de analyseopties), code invoer, of de resultaten. Als je geen keuze maakt, wordt het standaard lettertype gebruikt."

2020-09-01 09:16 UTC, TimKDJ commented
This is quite a bit more clean and it's also more clear what is going on.
However, I think it'd be good to:
- [ ]  Not make the default gray; it's unclear you can click this again to go back to your default
- [ ] Add a scrollbar, as mentioned by Joris
- [ ] Add a separator line between the default and the other fonts

I think this is done in a very neat way:
![chose-font](https://user-images.githubusercontent.com/18737241/91831536-78fd0300-ec44-11ea-9791-2284a6ecd350.png)

2020-09-01 21:55 UTC, JorisGoosen commented
Looking good Bruno!

But you should turn on clipping for the dropdown menu (or set the size right):
<img width="235" alt="afbeelding" src="https://user-images.githubusercontent.com/29062713/91910029-9070d600-ecae-11ea-9d9f-a58d50ca232f.png">

2020-09-01 21:56 UTC, JorisGoosen commented
^^

<img width="235" alt="afbeelding" src="https://user-images.githubusercontent.com/29062713/91910139-c01fde00-ecae-11ea-9978-63e136640c9b.png">

2020-09-03 15:09 UTC, merged