Translations update from Weblate
jasp-stats/jasp-desktop pull request #4306
Opened 2020-09-25 12:41 UTC by weblate

Translations update from [Weblate](https://hosted.weblate.org/projects/jasp/jasp-desktop/) for JASP/JASP desktop.

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/jasp/-/jasp-desktop/horizontal-auto.svg)

2020-10-06 13:05 UTC, vandenman requested changes
I only looked at the Dutch translations, some comments below.

2020-10-06 13:05 UTC, vandenman commented on JASP-Engine/JASP/po/R-nl.po
> +msgstr "Proportie van successen"
```suggestion
msgstr "Proportie successen"
```

2020-10-06 13:05 UTC, vandenman commented on JASP-Engine/JASP/po/R-nl.po
> +"posterior model niet zijn gedefinieerd."
```suggestion
"De grafiek kan niet worden gemaakt omdat de posterior model kansen "
"niet zijn gedefinieerd."
```
I'm not sure why this is on two lines instead of one though.

2020-10-06 13:05 UTC, vandenman commented on JASP-Engine/JASP/po/R-nl.po
> +msgstr "Sequentiële Posterior Bijweken"
```suggestion
msgstr "Sequentiële Posterior Bijwerken"
```
typo?

2020-10-06 13:05 UTC, vandenman commented on JASP-Engine/JASP/po/R-nl.po
> +"met een bètavorige verdeling voor parameter %1$s is de voorspellende "
```suggestion
"met een bèta prior verdeling voor parameter %1$s is de voorspellende "
```

2020-10-06 13:05 UTC, vandenman commented on JASP-Engine/JASP/po/R-nl.po
>  "ifthey were considered as individual models (without the existence of other "
```suggestion
"if they were considered as individual models (without the existence of other "
```
probably not for this PR, but that looks like a typo in the English.

2020-10-06 13:05 UTC, vandenman commented on JASP-Engine/JASP/po/R-nl.po
> +"Heeft u ten minste n=2 onderzoeken? Als de prior is afgekapt , is hij dan "
```suggestion
"Heeft u ten minste n=2 onderzoeken? Als de prior is afgekapt, is hij dan "
```

2020-10-07 06:52 UTC, FransMeerhoff commented on JASP-Engine/JASP/po/R-nl.po
> +msgstr "Proportie van successen"
Ok

2020-10-07 06:54 UTC, FransMeerhoff commented on JASP-Engine/JASP/po/R-nl.po
> +"posterior model niet zijn gedefinieerd."
Ok

2020-10-07 06:54 UTC, FransMeerhoff commented on JASP-Engine/JASP/po/R-nl.po
> +msgstr "Sequentiële Posterior Bijweken"
Ok

2020-10-07 07:04 UTC, FransMeerhoff commented on JASP-Engine/JASP/po/R-nl.po
>  "ifthey were considered as individual models (without the existence of other "
Ok

2020-10-07 07:11 UTC, FransMeerhoff commented on JASP-Engine/JASP/po/R-nl.po
> +"Heeft u ten minste n=2 onderzoeken? Als de prior is afgekapt , is hij dan "
Ok

2020-10-07 08:15 UTC, merged