Intervalplot
jasp-stats/jasp-desktop pull request #4351
Opened 2020-10-08 20:10 UTC by milenasophie

2020-10-08 20:17 UTC, milenasophie commented
@vandenman

2020-10-09 07:39 UTC, vandenman requested changes
The bulk of the changes look good! The functionality is almost there, only the y-axis looks a litte bit funny. After you fix the comments below I might have some more pedantic style comments but that's about it!

When you make changes, please do so on this branch then the pull request will be updated automatically. Once it's ready for another round of reviews just let me know with @.

2020-10-09 07:39 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +    IntervalPlots <- jaspResults[["IntervalPlots"]]
I know it's very pedantic, but just to be consistent with camelcase could you make the first letter lowercase?
```suggestion
    intervalPlots <- jaspResults[["intervalPlots"]]
```
see also https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/r-style-guide.md

2020-10-09 07:39 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +      jaspResults[["IntervalPlots"]]$position <- 11
So since the position is 11 (last at the moment), could you also move this code to appear last in the function? So below the scatter plots.

2020-10-09 07:39 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +    }
```suggestion
    y               <- na.omit(dataset[[.v(variable)]])
```
the other objects are unused right?

2020-10-09 07:39 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +    yBreaks <- JASPgraphs::getPrettyAxisBreaks(y)
```suggestion
    yBreaks <- JASPgraphs::getPrettyAxisBreaks(c(cdata[["lower"]], cdata[["upper"]]))
```
so the breaks here are based on the data `y` but not on the summary statistics of `y` (stored in `cdata`). As a consequence, the y-axis of the plots doesn't make sense: 

![image](https://user-images.githubusercontent.com/21319932/95554949-5a431680-0a11-11eb-99b4-268f664c3e71.png)

2020-10-09 07:39 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +      ggplot2::scale_y_continuous(breaks = yBreaks) + #, limits = yLimits) +
you can merge `ylab` and `scale_y_continuous`. Also, if you adjust the `yBreaks` like in the comment above then the commented part about the limits is a good idea.
```suggestion
      ggplot2::scale_y_continuous(name = variable, breaks = yBreaks, limits = range(yBreaks)) +
```

2020-10-09 07:39 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +  }
you're not using this function so you can just delete it :)
```suggestion
```

2020-10-27 21:45 UTC, milenasophie commented
I worked on the interval plot again and fixed the problems with the LOCK documents on my computer so that I don't get any errors anymore. However, there are no interval plots in the output when I built JASP. @vandenman do you know why this might be?

2020-10-28 07:52 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +  }
So the top line (which you didn't edit) is a return statement. That means that no code beyond this point is ever run, which explains why there are no interval plots in the output when you built JASP.

2020-10-28 07:52 UTC, vandenman commented
@milenasophie Can you also reindent the R code? Selecting your changes and pressing `Ctrl` + `i` in RStudio should do the trick.

2020-10-30 15:46 UTC, vandenman commented on JASP-Engine/JASP/R/descriptives.R
> +    intervalPlots <- jaspResults[["intervalPlots"]]
With the change below I do get a plot in the output!
```suggestion
    intervalPlots <- jaspResults[["IntervalPlots"]]
```

2020-10-30 17:24 UTC, milenasophie commented on JASP-Engine/JASP/R/descriptives.R
> +    intervalPlots <- jaspResults[["intervalPlots"]]
Perfect!! Me too. How do you like the output?

2021-02-10 12:39 UTC, vandenman commented
This is merged in https://github.com/jasp-stats/jaspDescriptives

2021-02-10 12:39 UTC, closed without merging