Add R source
jasp-stats/jasp-desktop pull request #4446
Opened 2021-01-15 16:56 UTC by boutinb

Add jaspQmlSource as jasResults object
Add Rsource in QML

Fix jasp-stats/INTERNAL-jasp#1211

2021-01-18 00:03 UTC, FBartos commented
Can I thoroughly test it once it's in a nightly? I didn't build JASP for ages and it would take me a long time to do so.

2021-01-18 09:01 UTC, boutinb commented
I think if @JorisGoosen reviews the code, then we can merge this PR, and you can test it.

2021-01-18 10:10 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +	connect(this,					&Analysis::RSourceChanged,	_analysisForm,	&AnalysisForm::rSourceChanged				);
RSourceChanged -> rSourceChanged ?

Wouldve been nicer if they were the same...

2021-01-18 10:22 UTC, JorisGoosen requested changes

2021-01-18 10:22 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +			if (colValue.isString())
I really think you should concatenate the columns if they are in the same row. Otherwise it will get confusing.

2021-01-18 10:22 UTC, JorisGoosen commented on Desktop/analysis/analysis.h
> +	std::map<std::string, Json::Value>	_RSources;
Shouldn't the first character always be small?

2021-01-18 10:22 UTC, JorisGoosen commented on Desktop/widgets/sourceitem.cpp
> +	_isColumnsModel			= map.contains("isDataSetColumns")			? map["isDataSetColumns"].toBool()			: false;
:)

2021-01-18 10:24 UTC, JorisGoosen commented
Mostly looks great, just two style-nitpicks and, as mentioned before, I think the columns in a row should be concatenated and not inserted one after the other into the resultlist.

Otherwise the list-length doubles directly on adding a column accidentally and would be consistent with any later extensions to have 2-dimensional lists.

2021-01-18 10:24 UTC, JorisGoosen commented
With those changes applied I would be fine with this being merged btw.

2021-01-21 14:41 UTC, JorisGoosen approved these changes
Now, if @FBartos can test whether it works like he intends to this can be merged.
I will turn on a nightly build of this for him.

2021-01-21 21:34 UTC, FBartos commented
@JorisGoosen nightly is the correct one? I will have (hopefully) some time on Friday afternoon to test it out

2021-01-24 18:46 UTC, FBartos commented
ok, I managed to make it running, looks exactly what I need but it crashes every time the source is NULL or a vector of length zero.

@boutinb, could you show me how to incorporate it into component list that creates Checkboxes?

2021-01-26 09:31 UTC, JorisGoosen approved these changes

2021-01-26 09:45 UTC, merged