Rewritten variables window
jasp-stats/jasp-desktop pull request #4455
Opened 2021-01-27 18:27 UTC by JorisGoosen

Taken from stable and modified slightly to work with Ctrl+Click for selecting multiple rows. 
And the normal click for a single row.

Shift+click was a nightmare. Ive left it out to get on with my life.

2021-02-02 16:31 UTC, boutinb requested changes
I still don't feel that it is really user-friendly. 
If we follow the Excel way, then single-click should select the row and you can already write into the cell. Double-Click should unselect the row, and you can only write into the cell.
Is that doable?

2021-02-02 16:31 UTC, boutinb commented on Desktop/qquick/datasetview.cpp
> -	previousContext->setContextProperty("isDynamic",		true);
Why did you change isDynamic to hasContextForm? The TableView controls need this context.

2021-02-03 11:21 UTC, JorisGoosen commented
> I still don't feel that it is really user-friendly.
> If we follow the Excel way, then single-click should select the row and you can already write into the cell. Double-Click should unselect the row, and you can only write into the cell.
> Is that doable?

I also don't feel this is userfriendly, but to get it working as you describe I would have to move all the selectioncode to `datasetview` which would require me to reselect everything there somehow after moving (now I just use a set of values).

I am getting quite sick of working on this to be honest. The selection column I added before was simple, worked fine and was easy to understand.
Now we have clicking that selects or not, doubleclicking and who knows what. Im going to simplify it. 

I'll just make it so that clicking on the value or around the textinput selects and clicking on the textinput will allow one to edit the text. Excel can go out of the window.

2021-02-04 11:37 UTC, JorisGoosen commented on Desktop/qquick/datasetview.cpp
> -	previousContext->setContextProperty("isDynamic",		true);
Ah that is a copy mistake!
But I also think it is a bit weird to have a property here that is always the exact same value... What is the point then?
But I'll fix it.

2021-02-04 11:38 UTC, JorisGoosen commented on Desktop/qquick/datasetview.cpp
> -	previousContext->setContextProperty("isDynamic",		true);
Also, the property "tableView" already tells your tableview it is a tableview right?
But still.. Ill fix it.

2021-02-15 10:35 UTC, boutinb commented
PR https://github.com/jasp-stats/jasp-desktop/pull/4463 takes it over.

2021-02-15 10:35 UTC, closed without merging