Added Key Navigation for RibbonBar
jasp-stats/jasp-desktop pull request #4497
Opened 2021-03-25 18:59 UTC by akashrajkn

## Description 

With "Ctrl + A", focus is given to the first element in the RibbonBar. You can switch between modules with Left and Right arrow keys. On pressing "Enter" key, the analysis menu open (if it exists). "Esc" hides the menu.  The menu can be navigated with Up and Down arrow keys. Pressing "Enter" key starts an analysis. 

#### Related Issue: jasp-stats/INTERNAL-jasp#1245

I tested it on Ubuntu 20.10
![jasp_key_navigation](https://user-images.githubusercontent.com/6959308/112528377-5bd87f00-8da4-11eb-832a-62b9c3498824.gif)

2021-03-25 19:02 UTC, akashrajkn commented
The submodules got commited. Any idea how to resolve this? I didn't make any changes in them and git diff doesn't show anything on my system

2021-03-30 08:52 UTC, boutinb requested changes
I'd like the following improvements:
. when you are at the last item of the ribbon, then with a right arrow, you go back to the first ribbon item (and if you are on the first item, a left arrow brings the focus to the last ribbon item). 
. when you are on a ribbon item, now you have to use return key to open the menu: it would be nice to have the space key and the bottom arrow to open the menu. If there is no menu (module with only 1 analysis), then only the return and space key starts the analysis (not the bottom arrow key).
. when you are on the analyses menu, also here, if you are at the bottom of the menu, the bottom array key brings you to the first analysis item (and the other way around).

2021-03-30 08:58 UTC, boutinb commented on Desktop/components/JASP/Widgets/CustomMenu.qml
> +                // There should be a better way to do this!
Yes. I think it is better to handle this in the model self. Here you are presuming that this is the menu for the analyses, but the CustomMenu is used in other situation. So let the model decide what to do with up and down action.

2021-03-30 09:30 UTC, boutinb commented on Desktop/components/JASP/Widgets/CustomMenu.qml
> +                // There should be a better way to do this!
Or you could add in the props an extra option (like functionCall): upCall, downCall. If they are not present, then a default up and down action can be defined.

2021-03-30 16:57 UTC, akashrajkn commented
I've incorporated the changes you mentioned. Can you check it out?

2021-04-01 11:39 UTC, JorisGoosen commented
It looks quite good already, I think it also needs some more changes.

For instance, it would be nice if navigation could skip the disabled ribbonbuttons.
Also nice would be to go left to the main menu button, and right to the module menubutton.

And then left from main menu, would be to module menu and vice versa.

2021-04-01 11:42 UTC, JorisGoosen requested changes
Those small changes I mentioned, for the rest it works really smoothly btw.

2021-04-01 12:25 UTC, boutinb approved these changes

2021-04-02 08:20 UTC, JorisGoosen commented
Aah, and @akashrajkn could you make the shortcut something else than "Ctrl+A" because that is typically the "select all" shortcut.
Maybe F2 would be good? Then we can use F1 for help or something.

2021-04-03 20:25 UTC, akashrajkn commented
>For instance, it would be nice if navigation could skip the disabled ribbonbuttons.
Also nice would be to go left to the main menu button, and right to the module menubutton.

I've added this in the latest one commit.

> Maybe F2 would be good? Then we can use F1 for help or something.

I wasn't able to change this. I replaced "Ctrl+A" sequence with Qt.Key_F2, but it is not being recognized. I left it as "Ctrl+A" for now.

2021-04-06 15:45 UTC, JorisGoosen commented
> > For instance, it would be nice if navigation could skip the disabled ribbonbuttons.
> > Also nice would be to go left to the main menu button, and right to the module menubutton.
> 
> I've added this in the latest one commit. I've updated the gif in description ;)

hah, thanks ^^
This is indeed better!

But... In the ribbon I can press "down" and go into the menu. I would expect this to work for main/module menus as well. But it doesn't. Only Enter.

Also, I would expect "escape" to close the menu and allow me to navigate the ribbonbar again (and this is what happens).
But it doesn't show the current button as "active" anymore so it looks a bit weird.
This is not superimportant though.

> 
> > Maybe F2 would be good? Then we can use F1 for help or something.
> 
> I wasn't able to change this. I replaced "Ctrl+A" sequence with Qt.Key_F2, but it is not being recognized. I left it as "Ctrl+A" for now.

Ok, well I really think that we cannot use Ctrl+A. Like really, it is totally unexpected. 
How about Ctrl+M ? for menu? Aaah wait, Ctrl+M is already for fullscreen :p

How about removing `Shortcut { onActivated: fileMenuModel.visible = !fileMenuModel.visible; sequences: ["Home",   Qt.Key_Home, Qt.Key_Menu];				}` and using those keys for `mainWindowRoot.changeFocusToRibbon()` ?

> 
> Also, the existing shortcut for full screen, Key_F11 doesn't work for me. However, if I change focus to some other element, say, Ribbons, I can catch F_key presses there. It only doesn't work in MainWindow.

Does Ctrl+M work for you though?
For me Ctrl+M works and F11 doesnt (on mac anyway)

> 
> **Other Changes**
> If a ribbon menu is open, Esc puts the focus to ribbon bar. From there another Esc removes the focus from ribbon bar entirely. If filemenubutton or modules menu button is focused, Esc removes focus from the ribbon bar entirely. I made this behaviour because in a future PR, I will be mergining navigation control from ribbon bar to analysis options and results view.

2021-04-06 22:53 UTC, akashrajkn commented
> Also, I would expect "escape" to close the menu and allow me to navigate the ribbonbar again (and this is what happens).
But it doesn't show the current button as "active" anymore so it looks a bit weird.
This is not superimportant though.

Fixed this

>In the ribbon I can press "down" and go into the menu. I would expect this to work for main/module menus as well.

I thought it was intuitive to have 'down' only if the element has a menu (so down won't work for Descriptives as well). Should I change this behaviour?

>How about removing Shortcut { onActivated: fileMenuModel.visible = !fileMenuModel.visible; sequences: ["Home", Qt.Key_Home, Qt.Key_Menu]; } and using those keys for mainWindowRoot.changeFocusToRibbon() ?

So, on the newer keyboard layouts, home keys are not always present. However the key sequence {"Fn" + Left arrow} is generally mapped to "Home". I think it's a bit counter-intuitive. Should I go ahead with it?

"Ctrl + M" works for me. F_keys don't work in MainWindow.
In many softwares, key navigation starts with a tab key press. That is also an option. What do you think?

2021-04-07 08:32 UTC, JorisGoosen commented
> > In the ribbon I can press "down" and go into the menu. I would expect this to work for main/module menus as well.
> 
> I thought it was intuitive to have 'down' only if the element has a menu (so down won't work for Descriptives as well). Should I change this behaviour?

In general regarding "a menu" as opening the "CustomMenu" is perfectly fine.
But the "main/file menu" and "modules menu" are also menus right?

> 
> > How about removing Shortcut { onActivated: fileMenuModel.visible = !fileMenuModel.visible; sequences: ["Home", Qt.Key_Home, Qt.Key_Menu]; } and using those keys for mainWindowRoot.changeFocusToRibbon() ?
> 
> So, on the newer keyboard layouts, home keys are not always present. However the key sequence {"Fn" + Left arrow} is generally mapped to "Home". I think it's a bit counter-intuitive. Should I go ahead with it?

Well, if it *is there* people can use it and I suppose "Fn+something" is not much worse than "Ctrl+something" anyway.

> 
> "Ctrl + M" works for me. F_keys don't work in MainWindow.
> In many softwares, key navigation starts with a tab key press. That is also an option. What do you think?

Hmm, well that is also a good one, but I would expect `tab` to also switch from area in gui to area. But I guess starting in the ribbonbar (if no data/workspace is loaded at least) makes a lot of sense.

For both of those btw, "Home/etc" and "tab-with-welcome" I would expect the focus to jump to the  main menu button.
What do you think?

2021-04-08 09:37 UTC, JorisGoosen commented
Aah you didn't do the tab thing right? No matter, that will be in the next PR then?

This is almost perfect!
Just one more thing....

When you are in the CustomMenu and you press escape now you are back in the ribbon and the button is selected again, very nice.
However, this doesnt happen for the FileMenu and ModuleMenu. If that is added then I will stop bothering you and this PR will be golden ^^

2021-04-09 08:28 UTC, boutinb commented
Om Mac, I did not know about the Fn-Left Arrow, but maybe this is standard...
One small thing: when I am on a Ribbon item, and I click with the mouse on another item, then the first item is still grayed out as is it still has the focus.

2021-04-12 10:22 UTC, JorisGoosen commented
Alright, almost there I think, one problem I saw was the following error:
`qrc:/components/JASP/Widgets/CustomMenu.qml:75: TypeError: Cannot read property 'forceActiveFocus' of null`
I think it could be good to put a little `if(menu.sourceItem !== null)` around:
```
menu.sourceItem.forceActiveFocus();
			if (menu.sourceItem.myMenuOpen !== undefined && typeof(menu.sourceItem.myMenuOpen) !== 'undefined')
				menu.sourceItem.myMenuOpen = true;
```

Then, what Bruno said is true. I think when the user clicks on a menubutton the keyboardfocus should also move there immediately. And then the "keyboardfocus-button" isn't shown as "pressed" while the "mouseclick-button" is *also*  shown as "pressed".

And I think that pressing left/right inside the menu when it is opened should be the same as pressing left/right on a button. But If you or @boutinb disagree with that then Im also fine with not having that.

2021-04-12 11:00 UTC, akashrajkn commented
Ah! I am in the process of fixing that. Also (Keyboard + Mouse) interactions are not smooth right now. I'll fix them and request a review

2021-04-12 14:54 UTC, JorisGoosen commented
Lekker bezig!

Ok, I will wait for your review-re-request then ^^

2021-04-17 14:08 UTC, akashrajkn commented
@JorisGoosen @boutinb I've made changes according to feedback. I've tested most of (key + mouse mix) navigation behaviours. Let me know if I missed any.

2021-04-19 12:11 UTC, JorisGoosen commented
Hey nice this works almost perfectly!

I just noticed a small problem where (for instance) I open debug and add "Descriptives" (which doesnt have a menu).
It keeps it looking "Pressed" ala:
![Screenshot_2021-04-19_140950](https://user-images.githubusercontent.com/29062713/115234264-1c8a1d80-a119-11eb-9e2e-55e5292a314d.png)

2021-04-21 14:00 UTC, JorisGoosen approved these changes
Ok awesome, the newest version works as expected and the code looks good, I totally approve.

2021-04-22 10:24 UTC, JorisGoosen commented
Ah you might need to rebase it now that I moved the `renv` branch into `development`.
Maybe you could also rebase+squash everything into a single commit?

2021-04-23 11:24 UTC, akashrajkn commented
Rebased and tested :)

2021-04-23 20:12 UTC, merged