Set the right type for the default value in TableView
jasp-stats/jasp-desktop pull request #4528
Opened 2021-05-27 07:33 UTC by boutinb

Fixes jasp-stats/jasp-test-release#1229

2021-06-01 13:13 UTC, Kucharssim commented
Also fixes jasp-stats/jasp-test-release#1230

2021-06-02 09:34 UTC, JorisGoosen requested changes

2021-06-02 09:34 UTC, JorisGoosen commented on Desktop/widgets/tableviewbase.cpp
> +	if (itemType() == JASPControl::ItemType::Integer)
This should be a switch

2021-06-03 11:57 UTC, boutinb commented on Desktop/widgets/tableviewbase.cpp
> +	if (itemType() == JASPControl::ItemType::Integer)
OK done

2021-06-07 08:58 UTC, JorisGoosen commented on Desktop/widgets/tableviewbase.cpp
> +	if (itemType() == JASPControl::ItemType::Integer)
You should rerequest a review ;)

2021-06-07 08:58 UTC, JorisGoosen commented on Desktop/widgets/tableviewbase.cpp
> +	}
You could've added a `default` here but I think GCC doesnt trust the switches too much, so this is not so bad.

2021-06-07 08:58 UTC, JorisGoosen approved these changes

2021-06-07 08:59 UTC, merged