Change language to Nederlands does not change the SEM menu
jasp-stats/jasp-desktop pull request #4546
Opened 2021-06-14 16:34 UTC by boutinb

This is because the SEM title does not change when the language is changed, and then the menu items.
Fixes jasp-stats/jasp-test-release#1340

2021-06-21 15:16 UTC, JorisGoosen requested changes
Uhm, instead of doing this the rough way, why not make sure that changes to the menu propagate?

The whole point of delayedUpdate is to group updates via QML.

So if none of the entries in the menu nor the title changes, then there needs to be no update to Description.

But if the problem is that the menu DOES change but it isn't visible in JASP... Well, that means that the menuchange ought to trigger this.

2021-06-21 16:41 UTC, boutinb commented
> But if the problem is that the menu DOES change but it isn't visible in JASP... Well, that means that the menuchange ought to trigger this.

OK, I use now the signals of the entryMenu.

2021-06-23 09:38 UTC, JorisGoosen reviewed
> > But if the problem is that the menu DOES change but it isn't visible in JASP... Well, that means that the menuchange ought to trigger this.
> 
> OK, I use now the signals of the entryMenu.

Can you "rerequest a review" next time? 
Because otherwise I see "changes requested" in the PR menu and think it won't be necessary to look at it. Luckily I remembered the email.

I'll go check it out now though ^^

2021-06-23 09:38 UTC, JorisGoosen commented on Desktop/modules/description/description.h
> +	void childChanged() { delayedUpdate(); }
But this slot already seems to call delayedUpdate?
So why do we need the connection? 

(And if we do not need it shouldn't it be a signal?)

2021-06-23 09:39 UTC, JorisGoosen commented on Desktop/modules/description/description.h
> +	void childChanged() { delayedUpdate(); }
Aah did I not post this before?

2021-06-23 09:40 UTC, JorisGoosen commented on Desktop/modules/description/description.cpp
> +	connect(this, &Description::childChanged,			this, &Description::delayedUpdate);
This is double isn't it?

like below

2021-06-23 09:52 UTC, JorisGoosen requested changes
`Description::childChanged` is a slot, but it is connected to `delayedUpdate` and it also calls it in the slot...

This doesn't make sense at all. Either it is a signal that triggers `delayedUpdate` or it is a slot and it calls it itself but then the connection should be removed.

I think I have a preference for the making `childChanged` a signal, ow that you've removed all the arguments that can work quite cleanly.

2021-06-23 09:52 UTC, JorisGoosen commented
I did test it and it does work so once that change has been made it can be merged ^^

2021-06-23 16:20 UTC, merged