Fix question punctuation: Remove . after ?
jasp-stats/jasp-desktop pull request #4563
Opened 2021-07-07 14:32 UTC by JoKeyser

Hi, just another small drive-by fix...

2021-07-08 07:12 UTC, boutinb approved these changes

2021-07-08 07:18 UTC, boutinb requested changes
I'm afraid that the translations made will be lost afterwards. You can directly change the po and pot files (in Desktop/po folder), to avoid the current translation to be removed.
I can do that also if you prefer.

2021-07-08 09:43 UTC, JoKeyser commented
@boutinb , oh yes, I had not thought about that problem. I will try to add these changes into the `.po` and `.pot` files later.

2021-07-08 12:18 UTC, JoKeyser commented
@boutinb , please have another look.

2021-07-09 06:20 UTC, boutinb approved these changes

2021-07-09 06:20 UTC, merged