add new reliability data sets
jasp-stats/jasp-desktop pull request #4635
Opened 2021-09-22 17:16 UTC by juliuspf

Before we only had data sets for the classical reliability analysis. 
This adds two more, one for the Bayesian unidimensional reliability analysis, and one for the classical intraclass correlation. 
I adjusted the "normal" index.json file. Should I also do the German one? Someone would need to do the dutch one then. Or will this process also be adjusted for the future so that things are "automatically" translated by the translators?

2021-09-23 08:46 UTC, Kucharssim commented
Yes, at this point, you need to modify `index_de.json` and `index_nl.json`, otherwise I think the files will not be available in those translations... Don likes to use DeepL for that purpose, but sometimes we just leave the text in english for now.

I think the plan was at some point to make the library dynamic so that people can add their files to their module repos without making PRs to `jasp-desktop` (https://github.com/jasp-stats/INTERNAL-jasp/issues/889). I think it makes sense to look at the translations at that point.

2021-09-23 08:50 UTC, juliuspf commented
Well, I can also just wait with these files and once there is the functionality to add them to the module directly do that. And then also think about the translations. It depends a bit on the timeframe for this, cause I would like to have some more examples for the reliability analysis some time soon-ish

2021-09-23 12:48 UTC, Kucharssim requested changes
Could you change the description in the saved files to be more similar to the other examples in the Data Library?
This is the part that I am talking about
![Screenshot 2021-09-23 at 14 43 12](https://user-images.githubusercontent.com/7093546/134508781-12c8e5f9-5a36-498f-8acc-0b5fc3639684.png)
![Screenshot 2021-09-23 at 14 43 03](https://user-images.githubusercontent.com/7093546/134508789-ce3f28fc-bff9-48b8-a7f9-c820826b2fde.png)

Which should be ideally structured like this:
![Screenshot 2021-09-23 at 14 43 36](https://user-images.githubusercontent.com/7093546/134508828-c8f3270b-f9a8-498f-b8ba-fb0d732d4d8c.png)

that is:
[
**Description**
What the data set is about

**Variables** 
list of variable names and what they represent

Then one, two sentences about what the jasp file demonstrates

**References**
]

> Well, I can also just wait with these files and once there is the functionality to add them to the module directly do that. And then also think about the translations. It depends a bit on the timeframe for this, cause I would like to have some more examples for the reliability analysis some time soon-ish

Yeah, I don't think that anyone is looking into it right now, so I would not bet that this will be implemented soon-ish... So if you want to add the data sets about now, it's better to do it this way... even though it's a bit annoying...

2021-09-24 08:49 UTC, Kucharssim requested changes
Just two small things in the jsons, otherwise it's good to go

2021-09-24 08:49 UTC, Kucharssim commented on Resources/Data Sets/index.json
> +		  }
On github, it seems that the indenting is off by one tab (in all three index files)

2021-09-24 08:49 UTC, Kucharssim commented on Resources/Data Sets/index_nl.json
>                }
```suggestion
              },
```
here needs to be comma for the json to work

2021-09-24 10:37 UTC, Kucharssim approved these changes

2021-09-24 10:38 UTC, Kucharssim commented
If @boutinb does not object, I would merge this

2021-09-24 10:43 UTC, boutinb approved these changes

2021-09-24 10:43 UTC, merged