Disabled the Exponent Aligning and Implemented the Normalized Notation
jasp-stats/jasp-desktop pull request #4646
Opened 2021-10-04 11:36 UTC by amirmasoudabdol

This partially addressed [this](https://github.com/jasp-stats/jasp-issues/issues/1437), and added an option for "normalized notation" as described [here](https://github.com/jasp-stats/INTERNAL-jasp/issues/1533). So, we will have 

![CleanShot 2021-10-04 at 13 22 18](https://user-images.githubusercontent.com/1290841/135844563-3fad017b-2477-44ff-841f-a88730d2bc79.png)

![CleanShot 2021-10-04 at 11 29 56](https://user-images.githubusercontent.com/1290841/135844594-a0f4a004-5d5c-4067-b313-448e65272c8b.png)

and this feature can be activated from the Table Options, 

![CleanShot 2021-10-04 at 13 26 15](https://user-images.githubusercontent.com/1290841/135844690-7754bb17-69e5-47df-935b-880de63b41ce.png)

I think I have tested this enough, and the exporting to HTML, RTF, and PDF works fine in my test. But, please give it a try, and let me know if you see something odd.

2021-10-04 15:52 UTC, djdekker commented
Nice to have the option to express 3.4400e+55 as 3.4400×10<sup>+55</sup>, which looks much more familiar to my students. Still one suggestion: dropping the + sign in front of a positive exponent would make it even more understandable: so I'd suggest to write 3.4400×10<sup>55</sup> instead of 3.4400×10<sup>+55</sup>. What would you think of that?

2021-10-04 17:20 UTC, EJWagenmakers commented
Great to see this fixed! I have a slight preference for omitting the plus sign, but there might be reasons to keep it (aligment, immediate contrast between numbers with + and -)...at any rate, this improves on what we did previously.

2021-10-05 07:09 UTC, amirmasoudabdol commented
Thanks for your feedback @djdekker. I totally agree with you, and in fact, I opened an internal discussion right after pushing this change. I agree with @EJWagenmakers thought that, here, the sign has some purpose, especially in the "e notation", less on the normalized notation.

That being said, I don't think keeping it _only to achieve_ alignment is a good idea, it's prone to break as soon as numbers are factors apart from each other, and as a result the contrast will not be preserved. As I argued [here](https://github.com/jasp-stats/INTERNAL-jasp/issues/1572), if we really want to, we can maybe offer an option like "Print Implicit Plus" which allows the user to ask for the `+` sign to appear on every number in the table. 

A more elaborate version of this option would be to allow for `+` sign in either base, exponent, or both. Let's say, a dropdown menu with three options, "Everywhere", "Only for base", "Only for exponent". But then, I am not a big fan of providing too many options, and I think a good default will go a long way, and in this case, a good default would be to just drop the sign in the "noramlized notation" and always include it in the "e notation". Perhaps we can discuss this further in the open discussion, and find a good middle ground.

2021-10-05 07:32 UTC, EJWagenmakers commented
+1

2021-10-25 09:56 UTC, JorisGoosen commented
Latex is broken:
![2021-10-25-115407_3840x2160_scrot](https://user-images.githubusercontent.com/29062713/138674872-24d7f527-97b2-4138-9d91-50428a03609c.png)

(I only tried this webinterface, but Im guessing it'll be the same in miktex or whatever)

`3.440×10$^{+56}$` is converted into `3.44010` with `+56` as superscript, but because the 10 is pasted on the beginnumber it becomes weird.

Besides that in JASP itself the natural notation doesn't line up, but maybe you weren't going for that yet?
![2021-10-25-115553_3840x2160_scrot](https://user-images.githubusercontent.com/29062713/138675173-56d96d51-3aa0-43aa-ac52-fa84231d059a.png)

2021-10-25 09:57 UTC, JorisGoosen requested changes
Latex should work as well

2021-10-25 10:03 UTC, amirmasoudabdol commented
Oh that's curious. I am pretty sure they passed my tests on several LaTeX engines. I am going to check it again. For the alignment, no, we shouldn't fix it by force. I'm going to look into it.

2021-10-25 10:20 UTC, amirmasoudabdol commented
I see the issue, they cannot get the `×` right in their engine. That's an unicode char and it should work but I can fix it for good by using `\times`! 👍🏼

2021-10-25 17:12 UTC, amirmasoudabdol commented
This fixes that issue, but I still cannot get a build on that website! 🤷🏻‍♂️ That's how the code looks like, and I can build it with pdfLaTeX, LuaLaTeX, and XeLaTeX on my Mac.

```tex
\begin{table}[h]
	\centering
	\caption{Descriptive Statistics}
	\label{tab:descriptiveStatistics}
	{
		\begin{tabular}{lrrrrr}
			\toprule
			 & contNormal & contGamma & contBinom & contExpon & contWide  \\
			\cmidrule[0.4pt]{1-6}
			Valid & $100$ & $100$ & $100$ & $100$ & $100$  \\
			Missing & $0$ & $0$ & $0$ & $0$ & $0$  \\
			Mean & $-0.19$ & $2.03$ & $0.42$ & $3.44\times10^{+55}$ & $-5.81\times10^{+97}$  \\
			Std. Deviation & $1.06$ & $1.53$ & $0.50$ & $3.44\times10^{+56}$ & $5.14\times10^{+99}$  \\
			Minimum & $-3.02$ & $0.20$ & $0.00$ & $1.74\times10^{-49}$ & $-8.96\times10^{+99}$  \\
			Maximum & $3.36$ & $8.77$ & $1.00$ & $3.44\times10^{+57}$ & $8.93\times10^{+99}$  \\
			\bottomrule
		\end{tabular}
	}
\end{table}
```

![CleanShot 2021-10-25 at 18 47 14](https://user-images.githubusercontent.com/1290841/138736843-87298a3c-09e5-4770-8e37-be182d173074.png)

I have tried to improve the `formatCellforLaTeX` implementation a bit but I can only do so much. The function should be aware of the type of the text that is receiving. With my changes, it tries to put all the numbers in a math block, and I think it should cover most cases. This addresses this one as well, https://github.com/jasp-stats/INTERNAL-jasp/issues/1572, by fixing the negative sign.

PS. JS is weird! It is fine for the most part, but then its type system is utterly broken! You can tell if something is a number by using `isNaN`!

2021-10-25 17:39 UTC, AlexanderLyNL commented
@akashrajkn could you provide some insights?

2021-10-26 08:41 UTC, akashrajkn commented
@amirmasoudabdol Your fix of using `$times` seems to work. On that website, there should be a expression `$$` somewhere in the line after `\toprule` (I don't know why), with that it renders
![Screenshot 2021-10-26 at 10-37-22 https quicklatex com](https://user-images.githubusercontent.com/6959308/138842585-7d80a2db-f715-4dfb-87d8-d624226e7822.png)

2021-10-28 15:30 UTC, JorisGoosen commented on Desktop/components/JASP/Widgets/FileMenu/PrefsResults.qml
> +				labelTextFormat:		Text.RichText
Was there a reason to add RichText here?

2021-10-28 15:30 UTC, JorisGoosen approved these changes

2021-10-28 15:30 UTC, merged