Alternative Background for the DMG file
jasp-stats/jasp-desktop pull request #4650
Opened 2021-10-11 09:31 UTC by amirmasoudabdol

Since many users are struggling with installing JASP, I thought let's put the instruction into the DMG file. Hopefully this will make it easier for us/them to deal with this situation until we have a better solution.

@boutinb, if we really want it out, let's push a silent update; otherwise we can wait for 0.16. Also, please check the outcome to make sure that the icons are placed correctly! 🙏🏼

![background](https://user-images.githubusercontent.com/1290841/136767268-6abe7704-01df-449c-acaa-065041906641.png)

It helps with this, https://github.com/jasp-stats/jasp-issues/issues/1426.

2021-10-11 10:46 UTC, djdekker commented
Thanks for your work! This should solve one of the issues that Mac users are experiencing when they start JASP.

Two other known Mac issues are:
- JASP is not registered as the default application to open .jasp files;
- JASP is not registered as a recommended application to open .csv files (see [issue 857](https://github.com/jasp-stats/jasp-issues/issues/857)).

Could these also be tackled with the script?

2021-10-11 10:53 UTC, amirmasoudabdol commented
@djdekker, this is a workaround and we will go back to the normal background as soon as we have a better solution, but I hope this helps.

As for the other issues, we are aware of them, and I thought it works but it doesn't work on my system, but it does on some others. Has it ever worked for you, across different JASP or macOS versions?

2021-10-12 12:36 UTC, boutinb commented
@amirmasoudabdol Did you try in a dmg? Because I get this
<img width="589" alt="Screenshot 2021-10-12 at 14 31 38" src="https://user-images.githubusercontent.com/503332/136956657-a6c035fb-a98e-4083-a9b2-9911258a2c32.png">

Als why did you add the background.svg file?

2021-10-12 12:39 UTC, amirmasoudabdol commented
@boutinb, Oh, ok, I messed the placement of that. The problem is, for some reason, my script cannot place the icon at all. You at least get something. Please try this instead:

```
set position of item "'${APP_NAME}'.app" of container window to {400, 660}
```

I included the SVG in case we want to edit it later.

I did try it, but since the JASP logo was not working for me at all, I couldn't test that part of it. I made sure that the Application fits properly and extrapolate form there.

2021-10-12 14:02 UTC, boutinb commented
If you set
```
set position of item "'${APP_NAME}'.app" of container window to {150, 640}
set position of item "Applications" of container window to {450, 640}
```
It works well on my machine.

2021-10-12 14:09 UTC, amirmasoudabdol commented
I think that should be good! Thanks Bruno!

2021-10-12 14:32 UTC, boutinb requested changes

2021-10-12 14:32 UTC, boutinb commented on Tools/macOS/sign-mac.sh
> -		set position of item "Applications" of container window to {360, 205}
Change the position in this way:
```
set position of item "'${APP_NAME}'.app" of container window to {150, 640}
set position of item "Applications" of container window to {450, 640}
```

2021-10-26 09:39 UTC, AlexanderLyNL commented
Merge this for 0.16

2021-11-03 09:32 UTC, amirmasoudabdol commented
@JorisGoosen, shouldn't this go in before the release?

2021-11-03 11:00 UTC, JorisGoosen approved these changes

2021-11-03 11:01 UTC, merged