Improvement to the MessageBoxes
jasp-stats/jasp-desktop pull request #4651
Opened 2021-10-11 16:22 UTC by amirmasoudabdol

I noticed this not so professional message, "There are unapplied changes to your filter; what would you like to do?", and while looking into that, I ended up improving the message box a bit. Because of macOS Guidelines, Qt cannot set the TitleBar text on macOS, and that makes the dialog looks a bit too bold. I don't expect this to break anything on Windows, but it's good to check it anyway.

@boutinb, I have changed a few labels and text, do I have to do anything for this to get into our translation portal?

![CleanShot 2021-10-11 at 18 15 47](https://user-images.githubusercontent.com/1290841/136822998-5a8c9e73-0a17-4602-9c98-3d14a626c77d.png)

![CleanShot 2021-10-11 at 18 12 05](https://user-images.githubusercontent.com/1290841/136823015-59f09aa7-1b92-4500-b45d-f31d68a8a73b.png)

2021-10-11 17:26 UTC, AlexanderLyNL requested changes
I think "Would you" is more suitable here. 

https://ell.stackexchange.com/questions/29804/what-is-the-difference-between-do-you-like-and-would-you-like

2021-10-11 17:26 UTC, AlexanderLyNL commented on Desktop/components/JASP/Widgets/ComputeColumnWindow.qml
> +			title:		qsTr("Do you want to save your changes to the Computed Column?")
Would you like to save your changes to the Computed Column?

2021-10-11 17:26 UTC, AlexanderLyNL commented on Desktop/components/JASP/Widgets/FilterWindow.qml
> +					title:	qsTr("Do you want to save your changes to the Filtered Column?")
Would you like to save your changes to the Filter?

2021-10-11 17:26 UTC, AlexanderLyNL commented on Desktop/mainwindow.cpp
> +			switch(MessageForwarder::showSaveDiscardCancel(tr("Do you want to save your changes to %1?").arg(title), tr("Your changes will be lost if you don't save them.")))
"Would you like to save your changes to %1 file?").arg(title), tr("Your changes will be lost if you don't save them."

2021-10-12 07:28 UTC, amirmasoudabdol commented on Desktop/components/JASP/Widgets/ComputeColumnWindow.qml
> +			title:		qsTr("Do you want to save your changes to the Computed Column?")
@AlexanderLyNL, I agree with this, but for some reason when I probed a few apps I realized that they don't go that far, and they often opt for "Do you", in some cases they even drop the "Do" and go with "Want to ..." (in the case of Microsoft Office apps). I think this is to make it make it more prominent, direct and prominent. But, if you think we should use "Would you", I am fine with that.

2021-10-12 07:38 UTC, AlexanderLyNL commented
To me the "Would you" construction works, but if prefer what microsoft does, then that's fine as well.

2021-10-12 07:40 UTC, amirmasoudabdol commented
Let's go with the "Would you" then!

2021-10-12 09:04 UTC, AlexanderLyNL approved these changes

2021-10-13 10:44 UTC, boutinb commented on Desktop/gui/messageforwarder.cpp
> +	box.setIcon(QMessageBox::Warning);
Why don't you use the warning method of QMessageBox?

2021-10-13 10:49 UTC, amirmasoudabdol commented on Desktop/gui/messageforwarder.cpp
> +	box.setIcon(QMessageBox::Warning);
Qt doesn't handle that properly on macOS. It ignores the title on macOS, then we end up with the before screenshot that I shared, everything gets cramped into a pseudo title. This way, on both systems, we get something similar.

> Sets the title of the message box to title. On macOS, the window title is ignored (as required by the macOS Guidelines). -- See setWindowTitle on [QMessageBox](http://doc.qt.io/qt-5/qmessagebox.html#setWindowTitle).

PS. I still cannot run a Windows VM on my Mac. So, I didn't test this on Windows, but it should not cause any issues because of the discrete way that I set the title.

2021-10-13 11:56 UTC, boutinb commented on Desktop/gui/messageforwarder.cpp
> +	box.setIcon(QMessageBox::Warning);
On Windows it was like that:
![OldMessage](https://user-images.githubusercontent.com/503332/137127620-33e5c0ed-a738-4a61-9506-f3c56bb41d05.png)
After your changes:
![NewMessage](https://user-images.githubusercontent.com/503332/137127650-282e009e-edb3-4088-bd4d-14bc843aa8bb.png)

So the 'File has changed' is not any more in the title, and the message is also smaller.

2022-01-07 16:29 UTC, boutinb approved these changes

2022-01-07 16:29 UTC, boutinb commented on Desktop/gui/messageforwarder.cpp
> +	box.setIcon(QMessageBox::Warning);
On Windows the text is not bold, so the informative text is not different than the text.
Moreover if you set the text in the constructor, Qt resize the Message Box according to the text. With your fix, it does not do that anymore. So I would do rather something like that:

```
QMessageBox box(QMessageBox::Question, title, message, QMessageBox::Yes | QMessageBox::No);
#ifdef Q_OS_MACOS
box.setText(title);
box.setInformativeText(message);
#endif

```

2022-01-10 13:17 UTC, amirmasoudabdol commented
@boutinb I see that to fix this properly, I need to change a few strings, and as you said this might make it tricky for the translators. I think I continue working on it, but we merge it after 0.16.1 that there is enough time for the translators to catch up. Is that a good idea?

2022-01-10 14:12 UTC, boutinb commented
Yes there is no need to implement this in 0.16.1

2023-06-01 10:50 UTC, JorisGoosen commented
Ok I rebased and updated the code to the current JASP version. But Im having trouble pushing to this branch.
So Ill open a new PR.

2023-06-01 10:50 UTC, closed without merging