[0.16.1] add jaspBsts
jasp-stats/jasp-desktop pull request #4667
Opened 2021-11-04 15:47 UTC by vandenman

Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1617

Note that the module is not completely finished yet (e.g., there are no unit tests), but @petersen-f is working on that.

2021-11-30 14:36 UTC, JorisGoosen commented on Desktop/mainwindow.cpp
> +		{ 	"jaspAudit", "jaspBain", "jaspCircular", "jaspDistributions" , "jaspEquivalenceTTests", "jaspJags", "jaspLearnBayes", "jaspMachineLearning", "jaspBsts",
I thought we were doing the modules in alphabetical order?

2021-11-30 14:37 UTC, JorisGoosen commented
So this all loos fine except for the order thing, this has to go in for 0.16.1 right?

2021-11-30 14:37 UTC, JorisGoosen requested changes
Sorry it is very nitpicky but if you can change the place where you inserted `jaspBsts` then this can be merged.

2021-12-01 09:34 UTC, JorisGoosen approved these changes

2021-12-01 09:39 UTC, JorisGoosen commented
Still no unit-tests though right?

Well, I see that some new work has been done in https://github.com/petersen-f/jaspBSTS but as the unittests (and perhaps other points) are still missing from jasp-stats/jaspBsts I think it is better to wait until those are in.

Especially given the upcoming feature stop.

2022-02-21 12:37 UTC, vandenman commented
@JorisGoosen happy to merge whenever you are! The unit tests are now fixed in the module.

2022-02-21 15:07 UTC, JorisGoosen approved these changes

2022-02-21 15:07 UTC, JorisGoosen commented
Aaah, I wanted to merge this but I think it is better to wait until the meeting tomorrow where we discuss 0.16.2

2022-02-21 15:56 UTC, vandenman commented
Didn't even know we were planning 0.16.2 but sounds like a good plan!

2022-02-21 16:24 UTC, EJWagenmakers commented
Definitely a good plan!

2022-04-26 13:32 UTC, vandenman commented
closed in favor of https://github.com/jasp-stats/jasp-desktop/pull/4764

2022-04-26 13:32 UTC, closed without merging