Default Built Type should be Release
jasp-stats/jasp-desktop pull request #4747
Opened 2022-04-06 11:10 UTC by boutinb

Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1797

2022-04-06 13:56 UTC, amirmasoudabdol commented
You don't need to do this on CMake. If the setting is not set, it'll be set to Debug but Qt Creator always sets it when you change the profile. So, you just need to change your profile when building and you get what you have selected.

2022-04-07 11:15 UTC, amirmasoudabdol requested changes
I think you should revert the CMake changes, and keep the rest.

2022-04-07 12:07 UTC, boutinb commented
OK, I've just kept the warning fixes.

2022-04-11 11:28 UTC, amirmasoudabdol approved these changes

2022-04-11 11:29 UTC, merged