add power and logit transforms
jasp-stats/jasp-desktop pull request #4799
Opened 2022-06-22 15:03 UTC by Kucharssim

closes https://github.com/jasp-stats/INTERNAL-jasp/issues/1728
closes https://github.com/jasp-stats/INTERNAL-jasp/issues/1866

2022-06-22 18:57 UTC, vandenman requested changes
So it looks all fine to me, except that `logb` doesn't seem to work (maybe the functionName should just be `log`?). It also shows up like this in the list:

![image](https://user-images.githubusercontent.com/21319932/175114086-3bf54ea3-e841-4155-8b77-edec6fdebe5a.png)

shouldn't it be `logb(y, b)`? Although some other functions, like `normalDist`, also accept multiple parameters but are shown without them.

Also, I was wondering if we should typeset inverse functions like `invLogit` like `logit⁻¹(y)`. On the one hand, `logit⁻¹(y)` is more readable (at least to me), while on the other hand, it's convenient that `invLogit` can also be used in the R code. Then again, there are a few other symbols that cannot be typed in R either: 
![image](https://user-images.githubusercontent.com/21319932/175114703-728a6acd-f683-4fe3-917e-a2b371878a11.png)

any thoughts?

2022-06-22 18:57 UTC, vandenman commented on Desktop/components/JASP/Widgets/ComputeColumnWindow.qml
> +					ListElement	{ type: "function";	functionName: "logb";			functionParameters: "y,base";			functionParamTypes: "number";						toolTip: qsTr("logarithm of y in 'base'") }
This doesn't seem to work for me:
![image](https://user-images.githubusercontent.com/21319932/175113612-96cb7f5f-fc0f-4c25-921a-02505734855f.png)

2022-06-23 05:53 UTC, Kucharssim commented on Desktop/components/JASP/Widgets/ComputeColumnWindow.qml
> +					ListElement	{ type: "function";	functionName: "logb";			functionParameters: "y,base";			functionParamTypes: "number";						toolTip: qsTr("logarithm of y in 'base'") }
it seems like you found an existing bug :) I will fix this

2022-06-23 06:21 UTC, Kucharssim commented
> Also, I was wondering if we should typeset inverse functions like invLogit like logit⁻¹(y). On the one hand, logit⁻¹(y) is more readable (at least to me), while on the other hand, it's convenient that invLogit can also be used in the R code. Then again, there are a few other symbols that cannot be typed in R either

Good point. I think the whole point of the point and click interface is to be human friendly (and not programmer friendly), so it does make sense to me to typeset it like logit⁻¹(y).

Just a question about implementation. I thought I could just change it to `logit\u207B\u00B9` (assuming unicode would work). However, it seems like we did not implement the option to replace the name of the function with another string? I could only replace it with an image like for the symbols here?

https://github.com/jasp-stats/jasp-desktop/blob/7c8c2a91fc914bc3a1c3b998611517d2fe0bdaf6/Desktop/components/JASP/Widgets/FilterConstructor/Function.qml#L17

 (If @vandenman does not know perhaps @JorisGoosen would). I must admit I am not happy about the prospect of making these images and in two themes 😅

2022-07-25 14:51 UTC, JorisGoosen commented
I could easily add a "pretty functionname" property and then you could enter the unicode directly there?

2022-07-25 15:38 UTC, Kucharssim commented
If you can easily add that, that would be nice!

2022-07-25 19:20 UTC, JorisGoosen commented
> If you can easily add that, that would be nice!

I added it to `stable` just now

2022-07-26 10:40 UTC, Kucharssim commented
For some reason I cannot build right now to test it, but the needed changes looked easy enough to make.

2022-07-26 11:49 UTC, vandenman commented
so this probably works, but because we no longer do `library(jaspBase)` by default I'm now seeing 

![image](https://user-images.githubusercontent.com/21319932/180998957-efe61863-8cbe-449c-a6ae-a3cb8b124608.png)

for all our custom functions...

2022-07-26 13:17 UTC, JorisGoosen commented
So... I can move https://github.com/jasp-stats/jasp-desktop/commit/e9e8011c7d663cfefc75eb3e23b05b390064b072 to `stable`

2022-07-26 16:08 UTC, vandenman commented
> So... I can move https://github.com/jasp-stats/jasp-desktop/commit/e9e8011c7d663cfefc75eb3e23b05b390064b072 to stable

I don't like it, but maybe it's best to do that for now. The downside is that every module needs to be aware that they should not clash with anything in `https://github.com/jasp-stats/jaspBase/blob/master/NAMESPACE`, but perhaps they should do that anyway because otherwise, we need to provide syntax with `jaspBase::` and `jaspModule::` rather than `library`.

2022-08-09 11:46 UTC, JorisGoosen commented
Ok, I moved the commit to `stable` so here it is: https://github.com/jasp-stats/jasp-desktop/commit/e4b61bc23767e1bb1c9d64b6ef6683880aed9a13

2022-08-09 11:47 UTC, JorisGoosen commented
so those custom functions should work again

2022-08-25 13:51 UTC, Kucharssim commented
Now it works!

There is just some funky business going on with the pretty labels:
![Screenshot 2022-08-25 at 15 47 08](https://user-images.githubusercontent.com/7093546/186682180-47ab9a18-f676-4c87-a574-a90c16dd67c5.png)

You can see on the right that the pretty labels are very pretty indeed, and they also look pretty if I drag them to the computation window alone, but if I drag it inside of another function, then the R function name is displayed instead of the pretty label (i.e., `logit(invLogit(contNormal))` should look like `logit(logit⁻¹((contNormal))`)

2022-08-25 14:27 UTC, JorisGoosen commented
Aah hey could you make a bug for it in 0.16.4? SHould be easy to fix but also to forget im afraid :p

2022-09-02 08:51 UTC, Kucharssim commented
Ok so this should be fine now, I guess @vandenman can give it a go once more but otherwise it should be ready

2022-09-02 11:17 UTC, vandenman commented
Looks good to me! The only nitpick I have is that the log2 and log10 should use subscript base rather than superscript base:

![image](https://user-images.githubusercontent.com/21319932/188127014-58450b59-ed3f-4baa-897b-3b8803caac50.png)

but Wikipedia (and others) do this:

![image](https://user-images.githubusercontent.com/21319932/188127056-666ff705-8793-4739-a743-9a3e28b651d4.png)

2022-09-06 07:58 UTC, Kucharssim commented
Thanks for spotting that! Should be fixed now

2022-09-06 08:58 UTC, vandenman approved these changes

2022-09-06 08:58 UTC, merged