Userdefined label for missing values in data
jasp-stats/jasp-desktop pull request #4833
Opened 2022-08-18 16:09 UTC by JorisGoosen

Implements https://github.com/jasp-stats/jasp-issues/issues/1708

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/29062713/185442301-57f1b087-c462-4d7b-b319-98f3dd81ffaa.png">

From JASP with love:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/29062713/185442696-850dd716-56f5-4f6c-85bd-3c659ab14dfa.png">

![Uploading image.png…]()

Haha, I like this feature + unicode support, such a colorful data view ^^

2022-08-23 17:01 UTC, boutinb requested changes
Quite tricky...
The Utils::emptyValue was expected to be always the empty string, but now it can be something else. You have changed the use of Utils::emptyValue in several cases so that in these cases it always use the empty string in place of the user-defined empty string. But you did not change it in Column::getOriginalValue: this method is used to display the value in a table, but is also used in DataSetPackage::writeDataSetToOStream which writes the data export file. So the data export will use the User defined empty string, which is not what is expected I think.

2022-08-23 17:01 UTC, boutinb commented on Desktop/utilities/settings.h
> -		REPORT_SHOW
What was this REPORT_SHOW?

2022-08-30 12:25 UTC, JorisGoosen commented on Desktop/utilities/settings.h
> -		REPORT_SHOW
accidentally committed it to `stable` but this is for `jaspReport` (for using jasp as a reportingtool)

2022-08-30 14:43 UTC, JorisGoosen commented on Common/column.cpp
> +	if (v > std::numeric_limits<double>::max())					return "∞";
much nicer like this right?

And its not like anyone wouldnt be using utf-8 by now.

2022-08-30 14:43 UTC, JorisGoosen commented on Desktop/data/datasetpackage.cpp
> -			if (value != ".")
this was apparently wrong for a while already :p

2022-08-30 14:44 UTC, JorisGoosen commented
I think ive fixed it all, would appreciate another look though @boutinb ^^

2022-09-06 10:58 UTC, boutinb approved these changes

2022-09-06 10:58 UTC, boutinb commented on Desktop/gui/preferencesmodel.h
>  	void dbShowWarningChanged(			bool		dbShowWarning);
Oeps: forgot to solve this conflict!

2022-09-06 10:58 UTC, merged