Allow Allowed & Suggested columns to be changed dynamically
jasp-stats/jasp-desktop pull request #4910
Opened 2022-11-07 16:18 UTC by boutinb

This is a request from @fqixiang 

The _setAllowedVariables function must be connected to the allowedColumnsChanged & suggestedColumnsChanged signals.
Moreover _setAllowedVariables should not mix up the _allowColumns & _suggestedColumns property: these properties should not be set in this function, only _variableTypesAllowed & _suggestedColumnsIcons should be set: _variableTypesAllowed is used to check which column is really allowed, and _suggestedColumnsIcons is used to set the icons in the VariablesList.

2022-11-09 11:08 UTC, JorisGoosen commented on QMLComponents/controls/variableslistbase.cpp
> +			if (type != columnType::unknown)
This check is kind of useless as `unknown` == 0 anyway. Although I guess it does make sense for the error/warning underneath.

2022-11-17 16:41 UTC, JorisGoosen commented
Did you fix this?

2022-11-18 14:20 UTC, boutinb commented
> Did you fix this?

It was working... I think you made a mistake when you tested it.

2022-11-22 13:15 UTC, JorisGoosen commented
If you set only suggested on a assigned form and no allowed (or just ordinal anyway) you get something that looks like:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/29062713/203322951-90255fa3-cad6-433c-a47e-0d15952d1875.png">

But then you can't actually drop anything there unless it is allowed as well...
Of course it is kind of silly to set both but in this case I would want to see only the join of `allowed & suggested ` instead of `allowed | suggested' as this looks confusing.

2022-11-22 13:16 UTC, JorisGoosen commented
Also weird: if nothing suggested and nothing allowed you cannot drop anything in an assigned field.
If only scale as suggested (for instance) you can then drop everything....

Edit:
In fact this only happens if you first select as "suggested"  "sacle + ordinal" and then remove first ordinal and then scale.
The variables disappear and you cant add anything anymore.

If I then turn scale back on I can add everything....

2022-11-22 13:18 UTC, JorisGoosen commented
also nominal text icon is wrong in darkmode:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/29062713/203323849-2e5e8cf8-c53d-4b46-95bf-29adbce87325.png">

2022-11-22 13:20 UTC, JorisGoosen commented
With a single "allowed type" that gets removed the assigned form remembers it. Not really a problem but ugly nonetheless.

2022-11-22 13:20 UTC, JorisGoosen requested changes
While it *does* indeed update dynamically now there are several issues Ive described and would like to see fixed or at least handled.

2022-11-24 15:08 UTC, boutinb commented
> Of course it is kind of silly to set both but in this case I would want to see only the join of `allowed & suggested ` instead of `allowed | suggested' as this looks confusing.

I don't want to change the current behaviour.
allowedColumns and suggestedColumns should normally not be used at the same time (maybe only for really specific goal, when you want for example to suggest 'nominal', and to have only this icon displayed, but allowing implicitly only 'ordinal', and not 'nominalText'. This can be achieved by using suggestedColumns set to 'nominal' and allowedColumns to 'nominal' and 'ordinal'. I don't know if this case will be ever used). 
I have updated the doc to describe more precisely how allowedColumns and suggestedColumns work and how they should be used.

2022-11-24 15:10 UTC, boutinb commented
> Edit:
> In fact this only happens if you first select as "suggested" "sacle + ordinal" and then remove first ordinal and then scale.
> The variables disappear and you cant add anything anymore.

This is now solved.

2022-11-24 15:11 UTC, boutinb commented
> With a single "allowed type" that gets removed the assigned form remembers it. Not really a problem but ugly nonetheless.

This is also solved.

2022-11-24 15:19 UTC, boutinb commented
> also nominal text icon is wrong in darkmode:
> <img alt="image" width="230" src="https://user-images.githubusercontent.com/29062713/203323849-2e5e8cf8-c53d-4b46-95bf-29adbce87325.png">
I get this:
![Screenshot 2022-11-24 at 16 17 48](https://user-images.githubusercontent.com/503332/203818374-8a6f7aaa-00f7-475f-8002-b0f2bffc32b1.png)

2022-11-29 13:43 UTC, JorisGoosen approved these changes

2022-11-29 13:43 UTC, merged