Add version to R Syntax
jasp-stats/jasp-desktop pull request #4933
Opened 2022-12-02 14:37 UTC by boutinb

Also 'data' and 'version' should be forbidden as option names.
Better handling of the option name, so that they don't conflict with each other, a formula name, or a reserved word.

2022-12-02 14:51 UTC, JorisGoosen commented on QMLComponents/controls/jaspcontrol.cpp
> +		// The control is created dynamically, this is the case for row components.
🙇

2022-12-02 14:55 UTC, JorisGoosen requested changes

2022-12-02 14:55 UTC, JorisGoosen commented on QMLComponents/rsyntax/rsyntax.cpp
> +	result += FunctionOptionIndent + "version = \"" + tq(AppInfo::version.asString()) + "\"";
This is wrong, you need to use the version of the module

2022-12-02 14:55 UTC, JorisGoosen commented on QMLComponents/rsyntax/rsyntax.cpp
> +	result += FunctionOptionIndent + "version = \"" + tq(AppInfo::version.asString()) + "\"";
as you should here

2022-12-05 12:41 UTC, JorisGoosen commented on QMLComponents/analysisbase.h
> +	virtual const Version & version()										const	{ return AppInfo::version;	}
Doesnt this mean that the versionnumbers in R-only mode will be totally wrong?

2022-12-05 12:43 UTC, JorisGoosen requested changes

2022-12-05 12:43 UTC, JorisGoosen commented on QMLComponents/analysisbase.h
> +	virtual const Version & version()										const	{ return AppInfo::version;	}
As in, with the current code all the stuff that has only access to AnalysisBase will always return whatever was the version of JASP when jaspBase gets compiled right?

Why not just add `_version` in AnalysisBase and not have an override in Analysis and then just make sure a value gets set into it.

2022-12-05 13:42 UTC, JorisGoosen requested changes
This is better... Except for a crucial problem.

The moduleversion is stored in `_moduleVersion` and the JASP version is `_version` .
_version isnt really used in JASP anymore I think.

2022-12-05 13:42 UTC, JorisGoosen commented
In fact, "version" on Analysis is there basically only to load jaspfiles from pre 0.15 jasps

2022-12-05 13:57 UTC, JorisGoosen commented
Maybe add that as a comment to the definition of `_version` in Analysis (as there is no reason to have the jasp-version specified when running in pure R anyway)

2022-12-06 15:34 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +		_moduleVersion = _dynamicModule ?  _dynamicModule->version() : AppInfo::version;
Why are you changing the behaviour?

2022-12-06 15:35 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +		_moduleVersion = _dynamicModule ?  _dynamicModule->version() : AppInfo::version;
this will all break loading old old files won't it?

2022-12-06 15:36 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +		_moduleVersion = _dynamicModule ?  _dynamicModule->version() : AppInfo::version;
```suggestion
	_moduleVersion = _dynamicModule->version();
```

2022-12-06 15:38 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> -	analysisAsJson["version"]		= _version.asString();
Its still useful to know which version of JASP was used to make an analysis right?

2022-12-06 15:39 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> -	analysisAsJson["version"]		= _version.asString();
Especially as the dynamic module might be, you know, dynamic

2022-12-06 15:39 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
>  	analysisAsJson["progress"]		= _progress;
```suggestion
	analysisAsJson["progress"]		= _progress;
	analysisAsJson["version"]		= _version.asString();
```

2022-12-06 16:22 UTC, JorisGoosen commented
I think some of those changes you made with regards to needsRefresh might have caused this bug:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/29062713/205966088-0e3eadd4-e58d-4464-b6c1-d6e81f03a20a.png">

Left is with your code and right is 0.16.4, file below:

[oudJaspFile-bLinReg.zip](https://github.com/jasp-stats/jasp-desktop/files/10168279/oudJaspFile-bLinReg.zip)

2022-12-06 16:27 UTC, boutinb commented on Desktop/analysis/analysis.cpp
> -	analysisAsJson["version"]		= _version.asString();
The _version is an obsolete property. Only _moduleVersion is used, and it is stored with the "dyamicModule" part of the json value (see Analyses::createFromJaspFileEntry)

2022-12-06 16:31 UTC, boutinb commented on Desktop/analysis/analysis.cpp
> +		_moduleVersion = _dynamicModule ?  _dynamicModule->version() : AppInfo::version;
Apparently for old JASP file, the _dynamicModule can be null, so it is here only to make it not crash, maybe I can then better set the  moduleVersion to 0.

2022-12-06 16:31 UTC, JorisGoosen requested changes

2022-12-06 16:31 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +		_moduleVersion = _dynamicModule ?  _dynamicModule->version() : AppInfo::version;
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/29062713/205967754-c018ed7f-fae6-494f-a012-6ec9b93219c1.png">

the right diff is from a log from your branch, it just loaded the attached file. 
[oudJaspFile-johnnyRfClassification.zip](https://github.com/jasp-stats/jasp-desktop/files/10168327/oudJaspFile-johnnyRfClassification.zip)

It should not have changed the version yet, as it hasn't been refreshed. I think this might cause the errormessage to dissappear

2022-12-06 16:32 UTC, JorisGoosen commented
So if you could change this PR to *not change the behaviour* that would be lovely.

So keeping "version" in there so we can track the original version of JASP used. 
And keep the `setVersion` function on Analysis, or was there a reason you removed it?

2022-12-06 17:00 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> +		_moduleVersion = _dynamicModule ?  _dynamicModule->version() : AppInfo::version;
First of all the upgrader handles `dynamicModule` being null, see: 
```
void DynamicModule::applyUpgrade(const std::string	& function,	const Version & version, Json::Value & analysesJson, UpgradeMsgs & msgs, StepsTaken & stepsTaken)
{
	if(!analysesJson.isMember("dynamicModule"))
		analysesJson["dynamicModule"] = asJsonForJaspFile(function);
	
	_upgrades->applyUpgrade(function, version, analysesJson, msgs, stepsTaken);
}
```

But it needs to have the information available to do this as seen at:
https://github.com/jasp-stats/jasp-desktop/blob/4bed733e759f11b14b19d0aa1f992221f21e07b9/Desktop/modules/upgrader/upgrader.cpp#L122

2022-12-06 17:01 UTC, JorisGoosen commented on Desktop/analysis/analysis.cpp
> -	analysisAsJson["version"]		= _version.asString();
I guess we could rely on the `version` in `Analysis` for the JASP version.

2022-12-07 12:43 UTC, JorisGoosen commented
Hmm, it seems the problem was already there in `stable`:
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/29062713/206182072-e450b59c-0794-4c80-aad3-551e266c3684.png">

Ill check your code again later.

2022-12-08 15:55 UTC, JorisGoosen approved these changes

2022-12-08 15:56 UTC, merged