extra space underneath last analysis
jasp-stats/jasp-desktop pull request #4938
Opened 2022-12-06 14:23 UTC by JorisGoosen

it isnt always perfect but I think Ive got the bases mostly covered:
- on add analysis, remove and move
- on change analysis (results updated)
- on reRender

Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2089

2022-12-07 12:56 UTC, JorisGoosen commented on Desktop/html/js/analyses.js
> +			height = height - lastAnalysis.$el.outerHeight();
```suggestion
			height = Math.max(0, height - lastAnalysis.$el.outerHeight());
```

2022-12-09 14:17 UTC, boutinb requested changes

2022-12-09 14:17 UTC, boutinb commented on Desktop/html/js/analyses.js
> +		var height		 = window.innerHeight;
Use better $(windows).innerHeight(): jQuery takes better into account the scrollbars.
I have noticed that when the horizontal scrollbar appears, then the bottomSpacer becomes a bit too high.

2022-12-09 16:34 UTC, JorisGoosen commented on Desktop/html/js/analyses.js
> +		var height		 = window.innerHeight;
```suggestion
		var height		 = $(windows).innerHeight();
```

like this?

2022-12-09 16:58 UTC, merged