Adds module selection to R commander
jasp-stats/jasp-desktop pull request #4940
Opened 2022-12-12 13:45 UTC by JorisGoosen

Also some feedback on what the engine is doing while the user waits. 
Fixes https://github.com/jasp-stats/jasp-issues/issues/1912

2022-12-12 16:35 UTC, boutinb requested changes
I have also remarked that if the output is quite long then you can scroll to the top of the output. This is not due to this PR, but maybe a good occasion to fix this.

2022-12-12 16:35 UTC, boutinb commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				height:			(codeRect.height - 2 * jaspTheme.generalAnchorMargin) / 4
It must be:

`(codeRect.height - 3 * jaspTheme.generalAnchorMargin) / 4`

2022-12-12 16:35 UTC, boutinb commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				//startValue:				 	"Module selection"
If you want a place holder use the properties:
```
placeholderText:			qsTr("Module selection")
addEmptyValue:			true
```

2022-12-12 16:35 UTC, boutinb commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				height:						runButton.height
The height does not change the height of the inner control (maybe not what is expected...). To change the height of the inner control:
`control.height:			runButton.height`

2022-12-12 16:48 UTC, JorisGoosen commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				height:			(codeRect.height - 2 * jaspTheme.generalAnchorMargin) / 4
can you make it a suggestion 
<img width="107" alt="image" src="https://user-images.githubusercontent.com/29062713/207104184-ced8f240-cf7c-4a64-9499-3c1a1b1d56fc.png">

2022-12-13 10:11 UTC, JorisGoosen commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				height:			(codeRect.height - 2 * jaspTheme.generalAnchorMargin) / 4
```suggestion
				height:			(codeRect.height - 3 * jaspTheme.generalAnchorMargin) / 4
```

2022-12-13 13:53 UTC, JorisGoosen commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				//startValue:				 	"Module selection"
Yeah I wanted to do that but now it just selects the first module anyway which is also fine by me.

2022-12-13 13:59 UTC, JorisGoosen commented on Desktop/components/JASP/Widgets/RCommanderWindow.qml
> +				height:						runButton.height
ah yes ok
```suggestion
				control.height:						runButton.height
```

2022-12-13 14:08 UTC, merged