Add police cadet ml dataset to data library
jasp-stats/jasp-desktop pull request #5035
Opened 2023-02-25 07:59 UTC by koenderks

Closes https://github.com/jasp-stats/jaspMachineLearning/issues/184

2023-02-25 14:34 UTC, vandenman requested changes
Looks good! A few very nitpicky comments:

![image](https://user-images.githubusercontent.com/21319932/221362532-5f13d9db-7b6c-4454-870e-85338b0e331a.png)

1. Green, the column label is `AvgG` but the description uses `AvG`.	
2. Yellow, should we add those labels to the dataset instead of just to the explanation?
3. red, `bayesian` should be `Bayesian`.

2023-02-25 14:34 UTC, vandenman commented on Resources/Data Sets/index.json
> +            "description": "Real-world data on police cadet evaluation, collected in the late 1990s in the Netherlands, which was used to study the effects of lowering admission standards and to pred
I would translate the name:
```suggestion
            "description": "Real-world data on police cadet evaluation, collected in the late 1990s in the Netherlands, which was used to study the effects of lowering admission standards and to predict whether cadets would pass the standard five-year evaluation based on various attributes. <br><br> <i>Data set made available by the National Police Corps and the Ministry of Justice of the Netherlands.<\/i>",
```

2023-02-26 07:52 UTC, koenderks commented
Thanks!

2023-02-28 08:37 UTC, vandenman approved these changes

2023-02-28 08:37 UTC, merged