some tweaks to jaspReport
jasp-stats/jasp-desktop pull request #5064
Opened 2023-04-17 11:58 UTC by JorisGoosen

make top notification better in jaspReport
make sure Desktopmain checks for --webEngineArgs as that is nowadays neccesary to debug via chrome

2023-04-17 12:01 UTC, JorisGoosen commented
This can be merged after 0.17.2 is released as well, no hurry.

2023-06-01 12:05 UTC, JorisGoosen commented
https://github.com/jasp-stats/jaspBase/pull/126 belongs with this
(Its commited as submodule in jaspBase btw)

Ive rebased it and it still seems to work, maybe time to merge this?
Btw it adds and activates jaspPredictiveAnalytics 

@petersen-f that is ok no?
@EJWagenmakers ?

2023-06-01 12:25 UTC, JorisGoosen commented
Oh wait there is still a small problem with the order of top notifications

2023-06-01 12:35 UTC, JorisGoosen commented
It should be fine now

2023-06-15 09:45 UTC, JorisGoosen commented
@boutinb  do you think you can check this out?

2023-06-15 10:36 UTC, boutinb requested changes
jaspBase is added in this commit... Should it be?

2023-06-15 10:36 UTC, boutinb commented on Desktop/html/js/analyses.js
> +
What does have to do with this PR?

2023-06-15 10:37 UTC, JorisGoosen commented
> jaspBase is added in this commit... Should it be?

Did you look at the commit?
Its the jaspReport branch as I mentioned: https://github.com/jasp-stats/jasp-desktop/pull/5064#issuecomment-1571929625

2023-06-15 10:38 UTC, JorisGoosen commented on Desktop/html/js/analyses.js
> +
this is to add topnotifications, when you click them you scroll to the analysis.
this is here to make the analsyses rerender themselves after they move so they can place their topnotification in the right z order

2023-06-15 14:29 UTC, boutinb approved these changes

2023-06-15 14:29 UTC, merged