Some fixes and improvements for data editing
jasp-stats/jasp-desktop pull request #5120
Opened 2023-06-20 11:47 UTC by JorisGoosen

- show warnings and stop the proxymodel from crashing all the time
- fix some "wrong model" errors
- added column title and description suppot
- variableswindow improvements so that title and description are editable and also usable for scalar columns
- general fixes

2023-06-20 14:35 UTC, boutinb requested changes
I have to test further, but at least 2 bugs found:

- The Variables Window shows the label/values 2 times
- The Variables types are not well passed to the VariablesList component.

2023-06-20 14:35 UTC, boutinb commented on Desktop/components/JASP/Widgets/VariablesWindow.qml
```suggestion
padding:			jaspTheme.jaspControlPadding
```

2023-06-20 14:35 UTC, boutinb commented on Desktop/components/JASP/Widgets/VariablesWindow.qml
> +
```suggestion
padding:			jaspTheme.jaspControlPadding
```

2023-06-20 14:47 UTC, JorisGoosen commented
>     * The Variables Window shows the label/values 2 times

Already fixed in https://github.com/JorisGoosen/jasp-desktop/tree/extendDataSet

>     * The Variables types are not well passed to the VariablesList component.

Ill check it out

2023-06-20 14:59 UTC, boutinb commented
Qua usability, this is quite strange to be able to change the labels in the Variables Window, but you can't change the column name, title or description as long as you are not in Edit Data mode. I think it's better to allow always this change.

It's also a pity to use the Qt TextInput and not the JASP TextField control, they don't have the same look and feel. But I can change this afterwards.

2023-06-21 08:16 UTC, JorisGoosen commented
> Qua usability, this is quite strange to be able to change the labels in the Variables Window, but you can't change the column name, title or description as long as you are not in Edit Data mode. I think it's better to allow always this change.

I agree!
I keep trying to click em :p
Ill change it

> It's also a pity to use the Qt TextInput and not the JASP TextField control, they don't have the same look and feel. But I can change this afterwards.

Yeah sure, good idea!

2023-06-21 10:13 UTC, boutinb commented
Hmm I have still 2 times the labels if I scroll to the right.
![Screenshot 2023-06-21 at 12 11 55](https://github.com/jasp-stats/jasp-desktop/assets/503332/425c6716-28fb-4872-8be4-080ce6abafa2)

Also I would set the description field just under the Name/Title TextFields

2023-06-21 10:15 UTC, boutinb commented
Also there are no lines above the header cells in the Variables Window

2023-06-21 10:20 UTC, boutinb commented
If I go to joris/furtherModelImprovements, it is much better.... so apperently you haven't updated  well upstream/furtherModelImprovements

2023-06-21 10:27 UTC, JorisGoosen commented
As i said, I fixed more things in the extendDataSet. Also everything from origin/further.. is in the upstream one

2023-06-21 10:30 UTC, JorisGoosen commented
<img width="1405" alt="image" src="https://github.com/jasp-stats/jasp-desktop/assets/29062713/86a99ca1-64d7-41e3-9c35-e2e806c348d9">
is in extendDataSet

2023-06-21 10:30 UTC, merged