Data Library - Meta-Analysis: Acculturation Mismatch and Intergenerational Cultural Conflict
jasp-stats/jasp-desktop pull request #5356
Opened 2023-12-15 18:06 UTC by FBartos

adds analyses based on Appendix A: Example Report from Bartoš et al. (2022) which showcases PET-PEESE, Selection Models, and RoBMA.

The issue is that fitting the RoBMA analysis would take ~ 30-90 min in JASP which is infeasible. As of now, I'm loading a precomputed model using a QML option and the RDS file [fit_RoBMA_Lui2015_light.zip](https://github.com/jasp-stats/jasp-desktop/files/13688449/fit_RoBMA_Lui2015_light.zip) (unzip). @vandenman says we can figure out how to add it to data library too maybe? :)

2023-12-19 11:40 UTC, JorisGoosen commented
https://github.com/jasp-stats/jasp-desktop/commit/0306a946c3907574658f32c5b9c68f31ebce8459#r135325575 ;)

2024-01-31 12:20 UTC, FBartos commented
now loads the file from the jaspMetaAnalysis module directly (https://github.com/jasp-stats/jaspMetaAnalysis/pull/217)

2024-02-01 09:16 UTC, vandenman requested changes
please add the changes also in https://github.com/jasp-stats/jasp-desktop/commit/0306a946c3907574658f32c5b9c68f31ebce8459#diff-501f918d32793b81db166daacae0b2161545fcac4dac27dec21d20f28961e929

2024-02-01 13:51 UTC, vandenman approved these changes

2024-02-01 13:51 UTC, merged