Fix TabView issues
jasp-stats/jasp-desktop pull request #5468
Opened 2024-04-15 16:09 UTC by boutinb

Fixes https://github.com/jasp-stats/jasp-issues/issues/2662 
Fixes https://github.com/jasp-stats/jasp-issues/issues/2661

The height of a TabView was not correctly set, especially when the height could vary dynamically.
Also the Tab buttons got a a new look so that selected button becomes more visible.

2024-04-17 13:00 UTC, JorisGoosen commented
Ok, the issue https://github.com/jasp-stats/jasp-issues/issues/2662 is solved now.


However, I still get the wrong height for switching models ( https://github.com/jasp-stats/jasp-issues/issues/2661 ):
<img width="640" alt="afbeelding" src="https://github.com/jasp-stats/jasp-desktop/assets/29062713/9926dd6e-aa3d-4152-9a27-1a95a2ac05e6">

<img width="626" alt="afbeelding" src="https://github.com/jasp-stats/jasp-desktop/assets/29062713/9ee4309f-1512-4fb0-9076-0c6cb576107f">

After adding model 3, 1 and 2 both have the wrong height.  In fact it seems that only the last model has the correct height.
Also after, for instance, removing the last one the then last one gets a correct height.

2024-04-18 13:20 UTC, JorisGoosen requested changes
Uh yeah, so I request that the height gets set properly ;)

2024-04-18 16:14 UTC, boutinb commented
I see with the pictures you show, that you did not use the right branch to test: the look & feel of the tab buttons is not the same:
<img width="627" alt="Screenshot 2024-04-18 at 18 12 50" src="https://github.com/jasp-stats/jasp-desktop/assets/503332/e91c87ec-e623-4c30-804c-947f9906b676">

2024-04-23 14:16 UTC, JorisGoosen approved these changes

2024-04-23 14:16 UTC, merged