add sem data example and clean up a bit in the data lib
jasp-stats/jasp-desktop pull request #5637
Opened 2024-08-06 15:20 UTC by juliuspfadt

2024-08-12 09:15 UTC, juliuspfadt commented
I didn't mean to update all these other files... can I revert that somehow?

2024-08-13 09:25 UTC, shun2wang commented
The most simple way is drop the last commit and re-add the `ADD symptoms` data files.

1. `git reset --hard HEAD~1`
2. add the data files
3. rebase upstreams head: `git rebase upstream/development`
4. froce push to upstream

2024-08-14 07:11 UTC, juliuspfadt commented
Thanks, I think I managed somehow :)

2024-09-05 15:29 UTC, boutinb commented
Hi @juliuspfadt I have added the json files so that the example will be seen in JASP menu. You still to add a description. There are translations for dutch, german and chinese. I think you can do the dutch and german translations easily. Maybe for the chinese translation, @shun2wang can help you?

2024-09-05 15:37 UTC, shun2wang requested changes
Ok, I had updated the translate.

2024-09-05 15:37 UTC, shun2wang commented on Resources/Data Sets/index_zh_Hans.json
>              "associated_datafile": "Interrater Data from Shrout and Fleiss (1979).csv"
```suggestion
            "associated_datafile": "来自 Shrout 和 Fleiss (1979).csv 评分者数据"
```

2024-09-06 12:55 UTC, juliuspfadt commented
I added the descriptions.

2024-09-06 13:25 UTC, boutinb commented
> ~Ok, I will updated the translate.~
> 
> there is no description should be translated I think? and I woud find a way to translate them with our Weblate hosts later.

The Data Library description is not yet in WebLate. This should be done before we have Module store. But for the time being, if you can translate the description (Julius just added it) in index_zh_Hans.json, then it will be translated in Chinese.

2024-09-06 13:28 UTC, shun2wang requested changes

2024-09-06 13:28 UTC, shun2wang commented on Resources/Data Sets/index_zh_Hans.json
> +            "description": "",
```suggestion
            "description": "数据样本由儿童（N=1163）的注意力缺陷障碍 (ADD) 症状进行评分构成，他们按照根据九个5分制李克特量表 (0-4)进行了打分（ Keulers & Hurks, 2021)。有序响应类别 0、1、2、3 、 4 表示特定症状行为的普遍性，范围从 0（从不）到 4（非常频繁）。对于 ADD 量表，总分越高，ADHD 症状越明显。该文件演示了分数相关标准测量误差的使用。",
```

2024-09-06 13:28 UTC, shun2wang commented on Resources/Data Sets/index_zh_Hans.json
> +            "description": "",
I just added chinese translations, thanks.

2024-09-06 13:31 UTC, shun2wang commented
>The Data Library description is not yet in WebLate. 

I mean I'm looking for a programmatic mechanism from json to po to translate the text, but that has nothing to do with this PR, I just think there might be a way to do it.

2024-09-06 14:44 UTC, juliuspfadt commented
I suppose @boutinb could merge it?

2024-09-09 07:48 UTC, boutinb commented
> Yes I know.I mean I'm looking for a programmatic mechanism from json to po to translate the text, but that has nothing to do with this PR, I just think there might be a way to do it.

I think we could add the names and the descriptions of the Library files in Description.qml with a new item DataLibrary with actually the same properties as the current index.json file, plus an extra property to tell whether the file should be present also in one or more books:
```
DataLibrary
{
          name: qsTr("Emily Rosa")
          path: "Emily Rosa.jasp"
          description: qsTr("Correct and incorrect decisions from therapeutic touch practitioners in Emily Rosa's famous experiment. \"In the initial trial, the subjects stated the correct location of the investigator's hand in 70 (47%) of 150 tries.\" <br><br> The example JASP file demonstrates the use of a Bayesian binomial test.<br><br> <i>Data set reconstructed from the summary information in Rosa et al. (1998).<\/i>")
          kind: "file",
          associated_datafile: "Emily Rosa.csv"
          books: ["Field"]
}
```

The books should be references to items that could be defined for example in DataLibrary.qml
```
Book
{
    name: "Field"
    label: qsTr("Field - Discovering Statistices"
    description: qsTr("...")
}
``` 

In this way all the string of the Data Library will be automatically in WebLate.

2024-09-09 07:49 UTC, merged

2024-09-09 07:54 UTC, shun2wang commented
Yes, good idea, actually the Weblate does [support ](https://docs.weblate.org/en/latest/formats/json.html) `.json` as translation source but I dont know how it works, maybe you can have a look? which may work without refactor I guess.