Fix bug where having empty values messes up labeledits
jasp-stats/jasp-desktop pull request #5666
Opened 2024-09-17 11:08 UTC by JorisGoosen

This is done by resetting labelsTemp

@kylelang this solves the problem you mentioned in the meeting?

For other (future) reviewers: 
Problem is that when you have a column like 'contBinom' and you change some values (in data editing) to a missing value (like NA) then editing the displayvalue of the label in the labeleditor will not update properly.
And from that point on further editing will make a mess of the data.

2024-09-17 11:14 UTC, kylelang commented
I was just about to hit the submit button on [my shiny new bug report](https://github.com/jasp-stats/INTERNAL-jasp/issues/2648), when you submitted this PR.

2024-09-23 09:30 UTC, kylelang commented
I don't think this PR fully fixes the bug. If I build JASP from your feature branch, recoding factor levels other than the first seems to work correctly now, but recoding the first factor level still breaks.

The types of variables that trigger the issue seem informative:

- The problem only arises when the column contains numeric-looking values and missing values represented as NA in the CSV.
- Missing values coded as NA don't cause problems when the rest of the values in the column are character labels.
- Numeric-looking columns with missing values coded some other way don't cause problems.

I spent some time in the debugger trying to locate the source of the issue.

The problem seems to stem from the way the `_labels` field of a `Column` object is populated and used.

In the problematic case, the call to `Column.setValues()` at [datasetpackage.cpp:1471](https://github.com/JorisGoosen/jasp-desktop/blob/8b57ec7807c96ce8ced16465853eeda975e212c5/Desktop/data/datasetpackage.cpp#L1471) creates a length-one entry in the `_labels` field of `column` where "NA" is recorded as the only label for the variable.

Since the other values are numeric-looking, the data ingress functions seem to assume that we'll be able to automatically generate labels from the numeric values when necessary. However, some of the downstream functions that trigger when editing labels seem to assume that either every value has a label or no labels exist. So, our Franken-variable breaks these functions.

As near as I can tell, the critical failure happens at [datasetpackage.cpp:850](https://github.com/JorisGoosen/jasp-desktop/blob/8b57ec7807c96ce8ced16465853eeda975e212c5/Desktop/data/datasetpackage.cpp#L850). The pointer defined here ends up pointing to the `_labels` field for "NA". The `index` object used here is generated from the (correct) row number in the label editor view, but the contents of `_labels` field don't match the label editor view.

2024-09-23 09:32 UTC, kylelang requested changes
I don't think this PR fully fixes the bug. If I build JASP from your feature branch, recoding factor levels other than the first seems to work correctly now, but recoding the first factor level still breaks.

The types of variables that trigger the issue seem informative:

- The problem only arises when the column contains numeric-looking values and missing values represented as NA in the CSV.
- Missing values coded as NA don't cause problems when the rest of the values in the column are character labels.
- Numeric-looking columns with missing values coded some other way don't cause problems.

I spent some time in the debugger trying to locate the source of the issue.

The problem seems to stem from the way the `_labels` field of a `Column` object is populated and used.

In the problematic case, the call to `Column.setValues()` at [datasetpackage.cpp:1471](https://github.com/JorisGoosen/jasp-desktop/blob/8b57ec7807c96ce8ced16465853eeda975e212c5/Desktop/data/datasetpackage.cpp#L1471) creates a length-one entry in the `_labels` field of `column` where "NA" is recorded as the only label for the variable.

Since the other values are numeric-looking, the data ingress functions seem to assume that we'll be able to automatically generate labels from the numeric values when necessary. However, some of the downstream functions that trigger when editing labels seem to assume that either every value has a label or no labels exist. So, our Franken-variable breaks these functions.

As near as I can tell, the critical failure happens at [datasetpackage.cpp:850](https://github.com/JorisGoosen/jasp-desktop/blob/8b57ec7807c96ce8ced16465853eeda975e212c5/Desktop/data/datasetpackage.cpp#L850). The pointer defined here ends up pointing to the `_labels` field for "NA". The `index` object used here is generated from the (correct) row number in the label editor view, but the contents of `_labels` field don't match the label editor view.

2024-09-23 09:47 UTC, JorisGoosen commented
```
1. Load the attached dataset.
2. Try to change the label for column = "b" value = "1" to some character string.
```

[toy.csv](https://github.com/user-attachments/files/17095499/toy.csv)

2024-09-24 12:00 UTC, JorisGoosen commented
Fixed it

2024-09-24 12:33 UTC, kylelang approved these changes
As far as I can tell, the bug looks fixed. Thanks!

2024-09-24 12:33 UTC, kylelang commented on Desktop/data/datasetpackage.cpp
This change seems to fix the remaining problems with the label indexing.

2024-09-24 12:34 UTC, kylelang commented
> Fixed it

Looks good. Thanks!

2024-09-24 13:54 UTC, merged