DropDown width issues solved
jasp-stats/jasp-desktop pull request #5753
Opened 2024-12-04 17:14 UTC by boutinb

2024-12-05 14:14 UTC, JorisGoosen requested changes
You see them now then?

2024-12-05 14:14 UTC, JorisGoosen commented on QMLComponents/components/JASP/Controls/ComboBox.qml
> +	property alias  controlText:			controlText
```
	property alias  controlText:			controlText
```
???

2024-12-05 14:14 UTC, JorisGoosen commented on QMLComponents/components/JASP/Controls/ComboBox.qml
> +	property alias  controlText:			controlText
```suggestion
	property alias  controlText:			control.text
```

Maybe you mean this?

2024-12-05 14:14 UTC, JorisGoosen commented on QMLComponents/controls/comboboxbase.h
> +	void _setLongestValue();
???
```suggestion
```

2024-12-05 14:24 UTC, boutinb commented on QMLComponents/components/JASP/Controls/ComboBox.qml
> +	property alias  controlText:			controlText
I forgot to remove this

2024-12-05 14:27 UTC, boutinb commented on QMLComponents/components/JASP/Controls/ComboBox.qml
> +	property alias  controlText:			controlText
No this property must be removed. `value` is already the value of the DropDown.

2024-12-05 15:24 UTC, JorisGoosen commented on QMLComponents/components/JASP/Controls/ComboBox.qml
> +	property alias  controlText:			controlText
So remove it then

2024-12-05 16:10 UTC, shun2wang approved these changes
DropDown now work well for me.

2024-12-06 10:54 UTC, boutinb commented
Should we merge it @JorisGoosen ?

2024-12-06 13:02 UTC, merged